import type { EnglishCatalog } from "./catalogTypes";

/** Canonical proper nouns and voice notes shared by every English catalog. */
export const CAT_ODYSSEY_GLOSSARY: EnglishCatalog = Object.freeze({
  "고양이 오디세이": "Cat Odyssey",
  "먀디세우스": "Meow-dysseus",
  "텔레-묘-쿠스": "Tele-meow-chus",
  "퍼-넬로페": "Purr-nelope",
  "아-포-나": "A-paw-na",
  "아포나": "A-paw-na",
  "퍼-씨": "Purr-ce",
  "제우-푸스": "Zeu-puss",
  "포-사이돈": "Paw-seidon",
  "포세이돈": "Paw-seidon",
  "캣-립소": "Cat-lypso",
  "나우시-캣": "Nausi-cat",
  "뮤-올로스": "Mew-olus",
  "아이올로스": "Mew-olus",
  "에우마이오스": "Eumaeus",
  "유-먀오스": "Eumaeus",
  "허르-먀오스": "Her-meows",
  "폴리-먀오무스": "Poly-meow-mus",
  "폴리-머오무스": "Poly-meow-mus",
  "안티-냐우스": "Anti-nyaus",
  "안티-클로이아의 영혼": "Anti-claw-ia's Ghost",
  "안티-클로이아": "Anti-claw-ia",
  "헬리-포스": "Heli-paws",
  "이타-캣": "Itha-Cat",
  "이타카": "Itha-Cat",
  "아르고냥": "Argo-nyan",
  "아르고스": "Argos",
  "티레시아스": "Tiresias",
  "스킬라-캣": "Scylla-Cat",
  "스킬라": "Scylla",
  "카리브디스": "Charybdis",
  "오기기아": "Ogygia",
  "파이아키아": "Phaeacia",
  "트리나키아": "Thrinacia",
  "아이아이에": "Aeaea",
  "라이스트리곤": "Laestrygonian",
  "사이렌": "Siren",
  "키클롭스": "Cyclops",
  "로토스": "Lotus",
});
