import type { EnglishCatalog, TranslationRule } from "../catalogTypes";

// Battle HUD, objectives, effect labels, combat log, and tutorial copy.
export const BATTLE_ENGLISH_CATALOG: EnglishCatalog = Object.freeze({
  "액티브 충전 가속": "Active Charge Speed",
  "잔상 연격": "Afterimage Strikes",
  "동료 발사": "Ally Launch",
  "전장 광선": "Arena Beam",
  "속박": "Bind",
  "화상": "Burn",
  "연쇄 반사": "Chain Ricochet",
  "연쇄 번개": "Chain Lightning",
  "돌진 밀치기": "Charge Knockback",
  "상태 정화": "Cleanse",
  "공격 지연": "Attack Delay",
  "교차 참격": "Cross Slash",
  "피해 분담": "Damage Redirect",
  "추격탄": "Follow-up Shot",
  "진형 붕괴": "Formation Broken",
  "체력 회복": "Heal",
  "충격 누적": "Impact Stacks",
  "낙뢰 접지": "Lightning Grounded",
  "직선 관통": "Line Pierce",
  "약점 표식": "Weak-point Mark",
  "거울 분신": "Mirror Clone",
  "반전 궤적": "Mirrored Trajectory",
  "집중 포화": "Focused Barrage",
  "선회 칼날": "Orbiting Blade",
  "대지 차원 친화": "Earth Affinity",
  "영체 차원 친화": "Spirit Affinity",
  "쌍둥이 차원문": "Paired Portals",
  "궤적 연장": "Extended Trajectory",
  "투사체 보호": "Projectile Guard",
  "밀어내기 파동": "Push Wave",
  "방사 발사": "Radial Launch",
  "몸집 변화": "Size Shift",
  "체력 재생": "Regeneration",
  "약점 간파": "Reveal Weak Point",
  "부활": "Revive",
  "운명의 부활": "Fated Revival",
  "방패 파괴": "Shield Break",
  "적 축소": "Shrink Enemy",
  "수면 누적": "Sleep Stacks",
  "감속": "Slow",
  "가속": "Haste",
  "정지 수비": "Stationary Guard",
  "기절": "Stun",
  "예고 연장": "Extended Telegraph",
  "임시 범퍼": "Temporary Bumper",
  "임시 벽": "Temporary Wall",
  "완전 예측": "Perfect Prediction",
  "추진 가속": "Velocity Boost",
  "영체 통과": "Spirit Phase",
  "약점 강화": "Weak-point Boost",
  "순풍": "Tailwind",
  "취기": "Tipsy",
  "유물 효과": "Relic Effect",
  "특수 효과": "Special Effect",
  "회복 준비": "Preparing Heal",
  "소환 준비": "Preparing Summon",
  "뒤로 당겨 발사": "Pull Back to Launch",
  "고양이를 발사 반대 방향으로 당긴 뒤 놓으세요.": "Pull the cat opposite the launch direction, then release.",
  "잡은 채 좌우 검은 여백이나 게임 창 밖으로 나가도 조준은 계속 이어집니다.": "Aim continues even if you drag into the side margins or outside the game window.",
  "마우스·터치 · 누른 채 당기고 놓기": "Mouse or touch · hold, pull, and release",
  "조준은 바로 취소": "Cancel Aim Instantly",
  "잘못 당겼다면 발사하기 전에 취소하고 다시 잡으세요.": "If the pull is wrong, cancel before launch and grab the cat again.",
  "마우스는 드래그 중 우클릭, 키보드는 Esc, 터치는 다른 손가락으로 한 번 탭합니다.": "While dragging, right-click; press Esc; or tap once with a second finger.",
  "첫 조준": "First Aim",
  "뒤로 당긴 만큼 힘이 커집니다. 예상선은 정답 전체가 아니라 첫 반사까지만 보여 줍니다.": "Power grows as you pull back. The guide shows only the first ricochet, not the full answer.",
  "창 밖까지 당겨도 유지 · 우클릭 / Esc / 두 번째 손가락 탭으로 취소": "Drag outside the window if needed · cancel with right-click / Esc / second-finger tap",
  "첫 반사": "First Ricochet",
  "벽에 닿은 각도만큼 반사됩니다. 정면이 막혔다면 벽을 경유해 옆이나 뒤를 노리세요.": "The cat reflects at the angle it hits the wall. If the front is blocked, bank a shot into the side or rear.",
  "첫 우정 연계": "First Friendship Combo",
  "날아가는 고양이가 동료에게 닿으면 그 동료의 우정 스킬이 한 번 발동합니다.": "When the launched cat touches an ally, that ally's Friendship Skill activates once.",
  "아군을 경유하면 접촉한 동료의 회복·연쇄탄·관통 등 고유 효과가 발동합니다.": "Touch an ally to trigger their unique heal, chain shot, pierce, or other effect.",
  "적 예고와 방패": "Enemy Warnings & Shields",
  "카운트다운과 붉은 범위를 먼저 읽고, 방패 적은 벽 반사로 옆이나 뒤를 노리세요.": "Read countdowns and red zones first. Bank shots around shielded enemies to hit their side or rear.",
  "해역 기믹": "Sea Mechanics",
  "지형마다 작동 대상이 다릅니다. 일부 장애물은 적도 막거나 피해를 주며, 위험 표식은 선원에게 적용됩니다.": "Terrain affects different targets. Some obstacles block or hurt enemies too, while danger marks apply to crew.",
  "스테이지 목표": "Stage Objectives",
  "격파 외에도 부위 파괴·생존·보호·봉인·탈출이 있으니 하단 목표를 확인하세요.": "Objectives also include breaking parts, survival, protection, sealing, and escape. Check the footer.",
  "전투 불능 없이 생존": "Survive with no allies down",
  "전투 불능 없이 · 남은 HP 65% 이상": "No allies down · at least 65% HP remaining",
  "전투 불능 없이 보호 완료": "Complete protection with no allies down",
  "전투 불능 없이 · 남은 HP 75% 이상": "No allies down · at least 75% HP remaining",
  "최고 연쇄 3 HIT 이상으로 봉인": "Seal with a best chain of at least 3 HIT",
  "최고 연쇄 5 HIT · 남은 HP 60% 이상": "Best chain 5 HIT · at least 60% HP remaining",
  "1성 · 스테이지 클리어": "1 Star · Clear the stage",
  "스테이지 클리어": "Clear the stage",
  "약점 피해": "Weak-point Damage",
  "대기 중 피해 감소": "Idle Damage Reduction",
  "첫 공격 카운트 지연": "Delay First Attack Countdown",
  "첫 발사 속도": "First-launch Speed",
  "관통 후 속도 유지": "Retain Speed after Piercing",
  "임시 벽 내구도": "Temporary Wall Durability",
  "연속 약점 보너스": "Consecutive Weak-point Bonus",
  "첫 클리어 재료": "First-clear Materials",
  "보스 피해": "Boss Damage",
  "후방 피해": "Rear-hit Damage",
  "우정 접촉 범위": "Friendship Contact Radius",
  "파괴 부위 피해": "Breakable-part Damage",
  "소용돌이 저항": "Whirlpool Resistance",
  "중량형 질량": "Heavy-class Mass",
  "첫 기절 지속": "First-stun Duration",
  "보스 부위 체력 표시": "Show Boss-part HP",
  "바람·해류 저항": "Wind & Current Resistance",
  "파괴 벽 피해": "Breakable-wall Damage",
  "아군 접촉 후 속도": "Speed after Ally Contact",
  "위험지대 이탈 회복": "Heal after Leaving Hazard",
  "위험 벡터 표시": "Show Hazard Vector",
  "저체력 반발력": "Low-HP Restitution",
  "항로 골드": "Route Gold",
  "전투당 최초 전투불능 부활": "Revive First Fallen Ally per Battle",
  "약화 지속시간": "Debuff Duration",
  "액티브 충전 속도": "Active Charge Speed",
  "화상 피해": "Burn Damage",
  "3번째 접촉 연쇄번개": "Chain Lightning on Third Contact",
  "충돌 위상 통과": "Phase through Collision",
  "첫 약점 치명타 확률": "First Weak-point Critical Chance",
  "최저 체력 재생": "Regenerate Lowest HP",
  "다음 적 행동 예고": "Preview Next Enemy Action",
  "예상 반사 횟수": "Predicted Ricochet Count",
  "현재 미연결": "currently inactive",
  "조작 준비 다시 보기": "Replay Control Practice",
  "첫 출항 준비": "Prepare for the First Voyage",
  "실전 출항": "Set Sail",
  "취소 연습으로": "Practice Cancelling",
  "r01-s01 실전에서 이어집니다": "Continue in the live r01-s01 battle",
  "고양이를 뒤로 당겼다가 놓아 보세요": "Pull the cat back, then release",
  "당긴 채 우클릭·Esc·두 번째 손가락 탭": "While pulling: right-click · Esc · second-finger tap",
  "준비 건너뛰고 출항": "Skip Practice and Set Sail",
  "적": "Enemy",
  "발사 준비 완료 · 실전에서는 놓는 순간 출발합니다": "Launch ready · in battle, the cat moves the moment you release",
  "조준 취소 완료 · 이제 다시 안전하게 잡을 수 있습니다": "Aim cancelled · you can safely grab the cat again",
  "고양이를 아래로 당겼다가 놓으세요": "Pull the cat downward, then release",
  "아래로 당긴 채, 놓기 전에 취소하세요": "Pull downward, then cancel before releasing",
  "전장을 정찰하는 중": "Scouting the battlefield",
  "구조 기록 저장을 다시 시도합니다.": "Retrying rescue-record save.",
  "증원": "Reinforcement",
  "아군 차례": "Ally Turn",
  "현재 차례": "Current Turn",
  "턴 1": "Turn 1",
  "캐릭터를 뒤로 당겨 발사하세요": "Pull the character back to launch",
  "항해 일시정지": "Voyage Paused",
  "전투는 멈춘 상태입니다. 빠른 설정은 즉시 저장됩니다.": "Battle is paused. Quick settings are saved immediately.",
  "전투 계속": "Resume Battle",
  "예상 반사선 표시 단계 변경": "Change predicted ricochet guide",
  "모션 줄이기 설정으로 비활성": "Disabled by Reduce Motion",
  "강한 타격의 카메라 반응": "Camera response to heavy impacts",
  "1× / 1.5× / 2× 순환": "Cycle 1× / 1.5× / 2×",
  "전투 포기": "Abandon Battle",
  "적 행동 속도를 저장하지 못했습니다": "Could not save enemy action speed",
  "빠른 설정을 저장하지 못했습니다": "Could not save quick settings",
  "터치 조준 취소 · 다시 당겨 발사하세요": "Touch aim cancelled · pull back to launch again",
  "스킬 배치를 취소했습니다": "Skill placement cancelled",
  "조준 취소 · 다시 당겨 발사하세요": "Aim cancelled · pull back to launch again",
  "적의 행동이 끝난 뒤 조준할 수 있습니다": "You can aim after the enemy action ends",
  "기절 상태 · 이번 차례에는 행동할 수 없습니다": "Stunned · cannot act this turn",
  "현재는 행동할 수 없습니다": "Cannot act right now",
  "현재 차례 고양이를 잡고 뒤로 당겨 발사하세요": "Grab the active cat and pull back to launch",
  "충돌 경로 계산 중…": "Calculating collision path…",
  "게임패드 조준 취소 · 다시 조준하세요": "Gamepad aim cancelled · aim again",
  "Esc 조준 취소 · 다시 당겨 발사하세요": "Esc cancelled aim · pull back to launch again",
  "왼쪽 스틱으로 조준하세요": "Aim with the left stick",
  "조준을 취소했습니다": "Aim cancelled",
  "실전 코치 · 한 번만 표시": "Live Coach · shown once",
  "왼쪽 스틱으로 위치 이동 · A 선택 · B 취소": "Move with left stick · A select · B cancel",
  "직격 훈련 · 첫 적중 표식": "Direct-hit Training · first-hit marker",
  "보호 대상 자동 조준 제외": "Protected targets excluded from auto-aim",
  "자유 조준 · 조작 잠금 없음": "Free Aim · no control lock",
  "일방벽 통과 방향 표시": "Show one-way wall direction",
  "흡입 방향 표시": "Show suction direction",
  "환경 벡터 표시": "Show environment vectors",
  "감속 범위 표시": "Show slow-field area",
  "약점 궤적 표식 활성": "Weak-point trajectory marker active",
  "기절 상태 · 이번 차례를 넘깁니다": "Stunned · skipping this turn",
  "조준 보조 꺼짐 · 캐릭터를 뒤로 당겨 발사하세요": "Aim Assist off · pull the character back to launch",
  "황금 직격 표식을 맞추도록 뒤로 당겨 보세요": "Pull back to hit the golden direct-hit marker",
  "청록색 차원문 출구 표식을 확인하고 발사하세요": "Check the teal portal-exit marker, then launch",
  "자유 조준 · 캐릭터를 뒤로 당겨 발사하세요": "Free Aim · pull the character back to launch",
  "직격 표식 확인": "Direct-hit marker",
  "출구 표식 확인": "Exit marker",
  "자유 조준": "Free Aim",
  "적 선단": "Enemy Fleet",
  "조준 잠김": "Aim Locked",
  "우정 연계": "Friendship Combo",
  "적의 반격을 확인하세요": "Watch the enemy counterattack",
  "항로 궤적 실행 중": "Executing voyage trajectory",
  "적의 반격": "Enemy Counterattack",
  "보호": "Guard",
  "재생": "Regen",
  "피해 -35%": "Damage −35%",
  "적 행동": "Enemy Action",
  "붉은 조준선 · 공격 범위 확인": "Red aim line · check attack range",
  "발사 중": "Launching",
  "행동 중": "Acting",
  "마지막 생존 캐릭터": "Last surviving character",
  "함께 발사할 동료 없음": "No ally available to launch",
  "구조할 전투불능 동료 없음": "No fallen ally to rescue",
  "READY · 눌러서 발동": "READY · select to activate",
  "첫 번째 포털 위치를 선택하세요": "Choose the first portal position",
  "임시 범퍼를 놓을 위치를 선택하세요": "Choose where to place the temporary bumper",
  "다른 캐릭터·적·기믹과 겹치지 않는 빈 공간을 선택하세요": "Choose empty space that does not overlap characters, enemies, or mechanics",
  "두 번째 포털 위치를 선택하세요": "Choose the second portal position",
  "아직 액티브 스킬을 사용할 수 없습니다": "The Active Skill is not ready yet",
  "돌진": "Charge",
  "원거리 사격": "Ranged Shot",
  "방패 전진": "Shield Advance",
  "광역 충격": "Area Impact",
  "회복·가속": "Heal & Haste",
  "분열 폭발": "Split Explosion",
  "증원 소환": "Summon Reinforcements",
  "사격": "Shot",
  "방패": "Shield",
  "광역": "Area",
  "지원": "Support",
  "분열": "Split",
  "소환": "Summon",
  "방향 봉인 각인": "Directional Seal Marks",
  "새 각도 각인": "New-angle Marks",
  "속성 봉인 각인": "Affinity Seal Marks",
  "수정 화음 적중": "Crystal Chord Hits",
  "노랫결 차단": "Song-wave Interrupts",
  "머리 연쇄": "Head Chain",
  "도끼 고리 연쇄": "Axe-ring Chain",
  "후방 진형 붕괴": "Rear-hit Formation Break",
  "부자 연계 · 핵 개방": "Father-son Combo · Core Open",
  "안전 항로 개방": "Safe Route Open",
  "⚠ 접촉 금지 · 수동 조준": "⚠ Do Not Touch · manual aim",
  "◆ 탈출": "◆ Escape",
  "액티브": "Active",
  "벌목 대상": "Felling Target",
  "껍질 파손": "Bark Broken",
  "쓰러짐 · 마무리": "Fallen · finish it",
  "벌목 완료": "Felling Complete",
  "뗏목 부품": "Raft Part",
  "조립 위치 이동": "Move to Assembly Point",
  "결속 완료": "Lashing Complete",
  "섬의 결속": "Island Bond",
  "결속 약화": "Bond Fraying",
  "결속 해방": "Bond Severed",
  "목표": "Objective",
  "각성 완료": "Awakened",
  "파괴됨": "Destroyed",
  "보호 중": "Protected",
  "실패": "Failed",
  "기절 · 행동 불가": "Stunned · cannot act",
  "행동 불가": "Cannot Act",
  "우정 스킬": "Friendship Skill",
  "액티브 READY!": "ACTIVE READY!",
  "액티브 스킬": "Active Skill",
  "증원 출현!": "Reinforcements!",
  "연계 순서 초기화": "Combo Order Reset",
  "전장 변화": "Battlefield Shift",
  "진형 변화!": "Formation Shift!",
  "위험 예고": "Hazard Warning",
  "강타": "Heavy Hit",
  "장애물 파괴!": "Obstacle Destroyed!",
  "스침": "Graze",
  "피해 상한": "Damage Cap",
  "유물 연쇄 번개": "Relic Chain Lightning",
  "위치 이동": "Moved",
  "사거리 밖": "Out of Range",
  "지원 완료": "Support Complete",
  "공격 완료": "Attack Complete",
  "엄폐!": "Covered!",
  "경로 차단": "Path Blocked",
  "보호 대상 피격": "Protected Target Hit",
  "전투 불능": "Down",
  "목표 진행!": "Objective Progress!",
  "항해 성공": "Voyage Complete",
  "엔드게임 승리 정산표를 저장하지 못했습니다.": "Could not save the endgame victory settlement.",
  "승리 정산표를 저장하지 못했습니다.": "Could not save the victory settlement.",
  "승리 기록을 안전하게 저장하는 중입니다": "Saving the victory record safely",
  "보상은 아직 지급되지 않았고 전투 정산표는 남아 있습니다.\n정산 준비 또는 저장에 성공한 뒤 보상 화면으로 이동합니다.": "Rewards have not been granted, and the battle settlement remains saved.\nThe reward screen opens after settlement preparation and saving succeed.",
  "저장 다시 시도": "Retry Save",
  "정산 다시 준비": "Prepare Settlement Again",
  "항구에서 복구": "Recover at Harbor",
  "제한 턴 초과": "Turn Limit Exceeded",
  "목표를 끝내기 전에 시간이 다했습니다.": "Time ran out before the objective was complete.",
  "다이아 60 · 전원 체력 50% · 추가 3턴": "60 Diamonds · all allies at 50% HP · +3 turns",
  "보호 목표 실패": "Protection Objective Failed",
  "파괴되거나 금지된 목표를 복구해야 합니다.": "The destroyed or forbidden objective must be restored.",
  "다이아 60 · 목표 복구 · 전원 체력 50%": "60 Diamonds · restore objective · all allies at 50% HP",
  "선원 전투 불능": "Crew Defeated",
  "모든 선원이 쓰러졌습니다. 진형과 충돌각을 바꿔 보세요.": "All crew members are down. Try a new formation and impact angle.",
  "다이아 60 · 현재 전투 유지 · 전원 체력 50%": "60 Diamonds · keep current battle · all allies at 50% HP",
  "항해 실패": "Voyage Failed",
  "고양이 여신의 구조": "Cat Goddess Rescue",
  "그대로 재도전": "Retry from Start",
  "사용하지 않은 구조 전투를 먼저 이어가세요": "Resume the unused rescue battle first",
  "구조 결제를 완료하지 못했습니다.": "Could not complete the rescue purchase.",
  "목표  ·  지정 부위 파괴": "Objective · Destroy designated parts",
  "목표  ·  뗏목 부품 운반 및 결속": "Objective · Move and lash raft parts",
  "목표  ·  잠든 선원 깨우기": "Objective · Wake the sleeping crew",
  "목표  ·  보호 대상에 닿지 않고 버티기": "Objective · Endure without touching protected targets",
  "목표  ·  기억의 불꽃 지키기": "Objective · Protect the Flame of Memory",
  "목표  ·  보호 대상 지키기": "Objective · Protect the target",
  "목표  ·  봉인 목표 활성화": "Objective · Activate seal targets",
  "목표  ·  출구 도달": "Objective · Reach the exit",
  "목표  ·  모든 적 격파": "Objective · Defeat all enemies",
  "감속 지대": "Slow Field",
  "바람": "Wind",
  "해류": "Current",
  "소용돌이": "Whirlpool",
  "음파": "Sound Wave",
  "차원문": "Portal",
  "낙뢰": "Lightning",
  "접촉 금지": "Do Not Touch",
  "이동 장애물": "Moving Obstacle",
  "일방 반사벽": "One-way Wall",
  "쇄도 파도": "Wave Front",
  "파도 돌진": "Wave Charge",
  "파도 예고": "Wave Warning",
  "휴면 · 현재 안전": "Dormant · currently safe",
  " · 증원": " · Reinforcement",
  " 외": " and more",
  "액티브 · ": "Active · ",
  " · ⚠ 예고": " · ⚠ Warning",
  "행동": "Action",
  " · 현재 미연결": " · currently inactive",
  " 감소": " reduction",
  "폭풍 뒤의 섬, 오기기아에서 귀향의 돛이 다시 오른다.": "On Ogygia, the island beyond the storm, the sails of homecoming rise once more.",
  "먀디세우스는 홀로 이타카로 향할 첫 별을 찾는다.": "Meow-dysseus searches alone for the first star that will lead him to Itha-Cat.",
  "파이아키아에서 시작된 회상은 과거 선원들과 연꽃 해역으로 돌아간다.": "The memories that began in Phaeacia return to old crewmates and the Lotus Sea.",
  "잠든 선원을 깨우면 옛 동료들이 다시 승선하고, 그 뒤 나우시-캣과의 인연도 이어진다.": "Wake the sleeping crew, and former companions will come aboard again—then the bond with Nausi-cat will continue.",
  "외눈 거인의 동굴은 정면 공격을 비웃는다.": "The one-eyed giant's cave laughs at frontal attacks.",
  "벽을 타고 후방으로 돌아가 눈과 갑옷의 틈을 노려라.": "Bank off the walls to reach the rear, then aim for the gap between eye and armor.",
  "뮤-올로스의 바람은 매 턴 궤적을 새로 쓴다.": "Mew-olus's winds redraw every trajectory each turn.",
  "힘보다 방향을 읽는 선장만이 바람 주머니를 지킬 수 있다.": "Only a captain who reads direction over force can protect the Bag of Winds.",
  "퍼-씨의 궁전에서는 벽도, 몸집도, 편도 계속 바뀐다.": "In Purr-ce's palace, walls, bodies, and loyalties keep changing.",
  "상태 효과와 일방 반사벽을 이용해 변신의 덫을 역이용하라.": "Use status effects and one-way ricochet walls to turn the transformation trap against itself.",
  "저승의 벽은 산 자의 눈에 완전히 보이지 않는다.": "The walls of the Underworld are not fully visible to living eyes.",
  "기억의 불꽃을 지키며 영체의 길을 따라 예언을 만나야 한다.": "Protect the Flame of Memory and follow the spirits' path to meet the prophecy.",
  "노래는 파동이 되어 동굴 전체를 덮친다.": "The song becomes a wave that washes over the entire cavern.",
  "울림의 순서를 끊고 커지는 위험 반경을 피해 나아가라.": "Break the sequence of echoes and advance while avoiding the growing danger radius.",
  "스킬라의 여섯 머리와 카리브디스의 소용돌이가 길을 가른다.": "Scylla's six heads and Charybdis's whirlpool divide the way ahead.",
  "부위를 차례로 파괴해 안전 항로를 직접 만들어야 한다.": "Destroy the parts one by one to carve out a safe route.",
  "태양의 섬에는 번개와 금지된 소가 기다린다.": "Lightning and forbidden cattle await on the Island of the Sun.",
  "욕심을 억누르고 청동 벽으로 낙뢰를 흘려보내라.": "Restrain your greed and channel the lightning through bronze walls.",
  "마침내 이타카. 그러나 귀향의 마지막 벽은 왕궁 안에 있다.": "At last, Itha-Cat. Yet the final barrier to homecoming lies within the palace.",
  "모든 동료와 쌓은 연계를 한 발의 완벽한 궤적으로 증명하라.": "Prove every bond forged with your companions in the perfect trajectory of a single shot.",
  "새로운 항로": "New Route",
  "새로운 바다가 귀향선을 부른다.": "A new sea calls the ship home.",
  "새로운 동료 · 승선": "New Crewmate · Aboard",
  "새로운 동료가 합류했다.": "A new crewmate has joined.",
  "편성 화면에서 능력을 확인할 수 있다.": "View their abilities on the Party screen.",
});

export const BATTLE_ENGLISH_RULES: readonly TranslationRule[] = Object.freeze([
  { pattern: /^적 행동\s*·\s*(\d+)턴째$/u, replacement: (_m, turn) => `Enemy Action · Turn ${turn}` },
  { pattern: /^턴 (\d+) \/ (\d+)$/u, replacement: (_m, turn, limit) => `Turn ${turn} / ${limit}` },
  { pattern: /^멈춤 · (.+)$/u, replacement: (_m, behavior) => `Stopped · ${behavior}` },
  { pattern: /^행동 중 · (.+)$/u, replacement: (_m, behavior) => `Acting · ${behavior}` },
  { pattern: /^다음 공격 · (.+)$/u, replacement: (_m, behavior) => `Next Attack · ${behavior}` },
  { pattern: /^(\d+)턴 · (.+)$/u, replacement: (_m, turn, behavior) => `${turn} turn${turn === "1" ? "" : "s"} · ${behavior}` },
  { pattern: /^(\d+)턴 이내 승리$/u, replacement: (_m, turns) => `Win within ${turns} turns` },
  { pattern: /^(\d+)턴 이내 · 최고 연쇄 4 HIT$/u, replacement: (_m, turns) => `Within ${turns} turns · best chain 4 HIT` },
  { pattern: /^(\d+)턴 이내 · 전원 생존 탈출$/u, replacement: (_m, turns) => `Escape within ${turns} turns · all allies survive` },
  { pattern: /^(\d+)턴 이내 · 전원 생존 · 남은 HP 55% 이상$/u, replacement: (_m, turns) => `Within ${turns} turns · all survive · at least 55% HP` },
  { pattern: /^(\d+)턴 이내 목표 파괴$/u, replacement: (_m, turns) => `Destroy the objective within ${turns} turns` },
  { pattern: /^(\d+)턴 이내 · 남은 HP 60% 이상$/u, replacement: (_m, turns) => `Within ${turns} turns · at least 60% HP remaining` },
  { pattern: /^(\d+)턴 이내 조립 완료$/u, replacement: (_m, turns) => `Complete assembly within ${turns} turns` },
  { pattern: /^(\d+)턴 이내 · 전원 생존 · 남은 HP 70% 이상$/u, replacement: (_m, turns) => `Within ${turns} turns · all survive · at least 70% HP` },
  { pattern: /^2성 · (.+)$/u, replacement: (_m, condition) => `2 Stars · ${condition}` },
  { pattern: /^3성 · (.+)$/u, replacement: (_m, condition) => `3 Stars · ${condition}` },
  { pattern: /^(\d+)턴 감소$/u, replacement: (_m, turns) => `${turns} turn${turns === "1" ? "" : "s"} shorter` },
  { pattern: /^유물 효과 · 적의 첫 공격 (\d+)턴 지연$/u, replacement: (_m, turns) => `Relic Effect · delay the enemy's first attack by ${turns} turn${turns === "1" ? "" : "s"}` },
  { pattern: /^조준 가이드\s+(.+)$/u, replacement: (_m, state) => `Aim Guide · ${state}` },
  { pattern: /^화면 흔들림\s+(.+)$/u, replacement: (_m, state) => `Screen Shake · ${state}` },
  { pattern: /^효과음\s+(.+)$/u, replacement: (_m, state) => `Sound Effects · ${state}` },
  { pattern: /^(\d+)% · 눌러 음소거$/u, replacement: (_m, amount) => `${amount}% · select to mute` },
  { pattern: /^눌러 (\d+)%로 복원$/u, replacement: (_m, amount) => `Select to restore ${amount}%` },
  { pattern: /^적 행동 속도\s+([\d.]+)×$/u, replacement: (_m, speed) => `Enemy Action Speed · ${speed}×` },
  { pattern: /^패드 조준 (\d+)% · A 발사 · B 취소$/u, replacement: (_m, power) => `Gamepad Aim ${power}% · A launch · B cancel` },
  { pattern: /^예상 반사 (\d+)회$/u, replacement: (_m, count) => `Predicted Ricochets ×${count}` },
  { pattern: /^차원문 출구 (\d+)개 예고$/u, replacement: (_m, count) => `Preview ${count} portal exit${count === "1" ? "" : "s"}` },
  { pattern: /^(.+)  ·  발사 강도 (\d+)%  ·  놓아서 출격  ·  우클릭 취소$/u, replacement: (_m, prefix, power) => `${prefix} · Launch Power ${power}% · release to launch · right-click to cancel` },
  { pattern: /^(.+) 공격 연출 중$/u, replacement: (_m, attacker) => `${attacker} is attacking` },
  { pattern: /^접촉 · (.+)$/u, replacement: (_m, skill) => `Contact · ${skill}` },
  { pattern: /^(\d+) 연타 · (\d+) 반사$/u, replacement: (_m, hits, ricochets) => `${hits} hits · ${ricochets} ricochets` },
  { pattern: /^(\d+) 반사$/u, replacement: (_m, ricochets) => `${ricochets} ricochet${ricochets === "1" ? "" : "s"}` },
  { pattern: /^피해 (\d+)% 분담$/u, replacement: (_m, amount) => `Redirect ${amount}% damage` },
  { pattern: /^(.+?)(?: (.+))? · (\d+)턴$/u, replacement: (_m, label, value, turns) => `${label}${value ? ` ${value}` : ""} · ${turns} turn${turns === "1" ? "" : "s"}` },
  { pattern: /^적의 행동 · (.+)$/u, replacement: (_m, enemy) => `Enemy Action · ${enemy}` },
  { pattern: /^(행동 중|현재 차례) · (.+)$/u, replacement: (_m, state, actor) => `${state} · ${actor}` },
  { pattern: /^다음 (.+) 외$/u, replacement: (_m, names) => `Next ${names} and more` },
  { pattern: /^다음 (.+)$/u, replacement: (_m, names) => `Next ${names}` },
  { pattern: /^(.+)의 차례$/u, replacement: (_m, actor) => `${actor}'s Turn` },
  { pattern: /^CHARGE (\d+) \/ (\d+)$/u, replacement: (_m, charge, required) => `CHARGE ${charge} / ${required}` },
  { pattern: /^(.+) 발동!$/u, replacement: (_m, skill) => `${skill} activated!` },
  { pattern: /^액티브 · (.+)$/u, replacement: (_m, label) => `Active · ${label}` },
  { pattern: /^(.+) · (\d+)턴$/u, replacement: (_m, label, turns) => `${label} · ${turns} turn${turns === "1" ? "" : "s"}` },
  { pattern: /^⚡ (\d+)연타$/u, replacement: (_m, strikes) => `⚡ ${strikes} strikes` },
  { pattern: /^⚠ 예고 (\d+)턴$/u, replacement: (_m, turns) => `⚠ warning in ${turns} turn${turns === "1" ? "" : "s"}` },
  { pattern: /^위험 부채 (\d+)×(\d+)°$/u, replacement: (_m, count, degrees) => `Danger Fans ${count}×${degrees}°` },
  { pattern: /^안전각 (\d+)°$/u, replacement: (_m, degrees) => `Safe Arc ${degrees}°` },
  { pattern: /^파동 (\d+)$/u, replacement: (_m, radius) => `Wave ${radius}` },
  { pattern: /^활성 · 중심 (\d+) 즉사권$/u, replacement: (_m, radius) => `Active · lethal center ${radius}` },
  { pattern: /^속도 (\d+)%$/u, replacement: (_m, amount) => `Speed ${amount}%` },
  { pattern: /^ · (\d+)턴$/u, replacement: (_m, turns) => ` · ${turns} turn${turns === "1" ? "" : "s"}` },
  { pattern: /^ · 위험 부채 (\d+)×(\d+)°$/u, replacement: (_m, count, degrees) => ` · Danger Fans ${count}×${degrees}°` },
  { pattern: /^ · 안전각 (\d+)°$/u, replacement: (_m, degrees) => ` · Safe Arc ${degrees}°` },
  { pattern: /^ · 파동 (\d+)$/u, replacement: (_m, radius) => ` · Wave ${radius}` },
  { pattern: /^활성(?: · 중심 (\d+) 즉사권)?(.*)$/u, replacement: (_m, radius, suffix) => `Active${radius ? ` · lethal center ${radius}` : ""}${suffix}` },
  { pattern: /^ · 중심 (\d+) 즉사권$/u, replacement: (_m, radius) => ` · lethal center ${radius}` },
  {
    pattern: /^(.+) · 속도 (\d+)%(.*)$/u,
    replacement: (_m, prefix, amount, suffix) => {
      const turn = /^ · (\d+)턴$/u.exec(suffix)?.[1];
      return `${prefix} · Speed ${amount}%${turn ? ` · ${turn} turn${turn === "1" ? "" : "s"}` : suffix}`;
    },
  },
  { pattern: /^(.+) · 턴을 넘깁니다$/u, replacement: (_m, state) => `${state} · turn skipped` },
  { pattern: /^PHASE (.+)$/u, replacement: (_m, phase) => `PHASE ${phase}` },
  { pattern: /^보호막이 피해 (\d+) 방어$/u, replacement: (_m, amount) => `Barrier blocked ${amount} damage` },
  { pattern: /^(.+)의 공격$/u, replacement: (_m, source) => `${source}'s Attack` },
  { pattern: /^목표 (\d+) \/ (\d+)$/u, replacement: (_m, current, required) => `Objective ${current} / ${required}` },
  { pattern: /^목표 (.+)$/u, replacement: (_m, progress) => `Objective ${progress}` },
  { pattern: /^(.+) · 전리품 정산 중$/u, replacement: (_m, stage) => `${stage} · calculating spoils` },
  { pattern: /^목표  ·  (\d+)턴 생존$/u, replacement: (_m, turns) => `Objective · Survive ${turns} turns` },
  { pattern: /^(.+) · 잔여 (\d+)$/u, replacement: (_m, objective, remaining) => `${objective} · ${remaining} remaining` },
  { pattern: /^항로 (\d+) · 항해 서장$/u, replacement: (_m, route) => `Route ${route} · Voyage Prelude` },
  { pattern: /^(.+), (.+)이\(가\) 아르고냥의 항해에 합류했다\.$/u, replacement: (_m, epithet, name) => `${epithet} — ${name} has joined Argo-nyan's voyage.` },
  { pattern: /^(.+) · 아군이 이 동료와 접촉하면 즉시 발동한다\.$/u, replacement: (_m, skill) => `${skill} · Activates immediately when an ally touches this crewmate.` },
  { pattern: /^(\d+)턴$/u, replacement: (_m, turns) => `${turns} turn${turns === "1" ? "" : "s"}` },
  { pattern: /^(\d+)턴(.+)$/u, replacement: (_m, turns, suffix) => `${turns} turn${turns === "1" ? "" : "s"}${suffix}` },
]);
