import type { EnglishCatalog, TranslationRule } from "../catalogTypes";

// Data, story, character, item, and cutscene translations are kept separate
// from scene chrome so narrative terminology can be reviewed as one unit.
export const CONTENT_ENGLISH_CATALOG: EnglishCatalog = Object.freeze({
  // Playable heroes, epithets, and skills.
  "먀디세우스": "Meow-dysseus",
  "귀향의 책략가": "Homecoming Strategist",
  "이타-캣의 화살비": "Itha-Cat Arrowstorm",
  "아무도 아닌 자의 궤적": "Nobody's Trajectory",
  "텔레-묘-쿠스": "Tele-meow-chus",
  "성장하는 왕자": "Prince in the Making",
  "푸른 망토 돌진": "Blue Cloak Charge",
  "부자의 귀환": "Father and Son's Return",
  "아-포-나": "A-paw-na",
  "푸른 볏의 수호자": "Guardian of the Blue Crest",
  "고르곤 방패": "Gorgon Shield",
  "신탁의 창": "Spear of the Oracle",
  "퍼-넬로페": "Purr-nelope",
  "베틀의 왕비": "Queen of the Loom",
  "풀리지 않는 직조": "The Unending Weave",
  "침대의 비밀": "Secret of the Bed",
  "캣-립소": "Cat-lypso",
  "오기기아의 별": "Star of Ogygia",
  "불사의 덩굴": "Immortal Vines",
  "머무는 시간": "Lingering Time",
  "나우시-캣": "Nausi-cat",
  "해변의 구원자": "Rescuer on the Shore",
  "물결 공놀이": "Wave Ball",
  "환대의 해변": "Shore of Hospitality",
  "노잡이 미로스": "Miros the Oarsman",
  "주황 선원": "Orange Sailor",
  "일제 노젓기": "Row as One",
  "닻 내리기": "Drop Anchor",
  "돛잡이 네로스": "Neros the Sailhand",
  "턱시도 선원": "Tuxedo Sailor",
  "돛줄 베기": "Cut the Rigging",
  "순풍 전환": "Turn the Tailwind",
  "에우마이오스": "Eumaeus",
  "충직한 목동": "Faithful Swineherd",
  "목동의 울타리": "Herdsman's Fence",
  "변치 않는 충성": "Unwavering Loyalty",
  "아르고스": "Argos",
  "늙은 문지기": "Old Gatekeeper",
  "주인을 알아본 눈": "The Master's Knowing Eyes",
  "마지막 질주": "Final Dash",
  "뮤-올로스": "Mew-olus",
  "바람의 왕": "King of the Winds",
  "봉인된 순풍": "Sealed Tailwind",
  "여덟 바람 해방": "Unleash the Eight Winds",
  "퍼-씨": "Purr-ce",
  "아이아이에의 마녀": "Witch of Aeaea",
  "변신 약초": "Transforming Herb",
  "마법 거울 회랑": "Hall of Magic Mirrors",
  "티레시아스": "Tiresias",
  "저승의 예언자": "Prophet of the Underworld",
  "다가올 공격": "Attack Foretold",
  "귀향의 예언": "Prophecy of Homecoming",
  "안티-클로이아의 영혼": "Anti-claw-ia's Ghost",
  "기억의 어머니": "Mother of Memory",
  "영체 통과": "Spirit Passage",
  "잊지 못할 품": "An Embrace Never Forgotten",
  "헬리-포스": "Heli-paws",
  "태양 바퀴의 수호자": "Guardian of the Sun Wheel",
  "태양륜": "Sun Wheel",
  "정오의 심판": "Judgment at Noon",
  "허르-먀오스": "Her-meows",
  "날개 달린 전령": "Winged Messenger",
  "전령의 잔상": "Messenger's Afterimage",
  "신들의 지름길": "Shortcut of the Gods",

  // Enemy behavior contracts and enemy names.
  "돌진": "Charge",
  "진행 방향을 부채꼴로 표시한다.": "Shows its direction of travel as a cone.",
  "가장 가까운 영웅을 향해 직선 돌진하고 벽에서 한 번 반사한다.": "Charges straight at the nearest hero and ricochets off one wall.",
  "사격": "Ranged",
  "발사선과 착탄 원을 표시한다.": "Shows the firing line and impact circle.",
  "카운트 종료 시 표시된 선을 따라 투사체를 발사한다.": "Fires a projectile along the marked line when the countdown ends.",
  "방패": "Shield",
  "보호 방향과 무효 부채꼴을 표시한다.": "Shows the guarded direction and the cone that blocks attacks.",
  "정면 충돌을 감쇠하고 후면 충돌에는 추가 피해를 받는다.": "Reduces frontal impacts but takes extra damage from behind.",
  "중량": "Heavy",
  "충격파 반경과 낙하지점을 표시한다.": "Shows the shockwave radius and impact point.",
  "이동하지 않거나 짧게 움직이며 넓은 충격파를 발생시킨다.": "Stays still or moves a short distance, then creates a wide shockwave.",
  "지원": "Support",
  "강화 또는 회복 대상과 연결선을 표시한다.": "Links to the ally it will strengthen or heal.",
  "아군을 회복하거나 공격 카운트를 앞당긴다.": "Heals an ally or advances its attack countdown.",
  "분열": "Splitter",
  "분열 방향과 생성 위치를 표시한다.": "Shows the split directions and spawn positions.",
  "첫 파괴 시 작은 개체 둘로 나뉜다.": "Splits into two smaller creatures when first destroyed.",
  "소환": "Summoner",
  "소환 문양과 생성 슬롯을 표시한다.": "Shows the summoning sigil and spawn slots.",
  "빈 슬롯에 지정된 하수인을 소환한다.": "Summons its designated minions into empty slots.",
  "거품 게": "Foam Crab",
  "암초 멧고양이": "Reef Wildcat",
  "폭풍 숫양고양이": "Storm Ramcat",
  "궁전 추격묘": "Palace Houndcat",
  "로토스 씨앗사수": "Lotus Seedspitter",
  "산호 궁수": "Coral Archer",
  "망령 궁수": "Shade Archer",
  "구혼자 투창수": "Suitor Javelinier",
  "청동 방패묘": "Bronze Shieldcat",
  "조개 방패병": "Shell Guard",
  "구혼자 호플론": "Suitor Hoplon",
  "외눈 동굴수문장": "One-Eyed Cave Guard",
  "바위 등딱지묘": "Rock-Shell Cat",
  "라이스트리곤 거인묘": "Laestrygonian Giantcat",
  "저승의 문지기": "Keeper of the Underworld",
  "신성한 소 수호령": "Sacred Cattle Guardian",
  "파도 찬가묘": "Tide Chanter",
  "로토스 향료묘": "Lotus Perfumer",
  "망령 예언묘": "Shade Oracle",
  "사이렌 합창묘": "Siren Chorister",
  "분열 말미잘": "Splitting Anemone",
  "저승 도깨비불": "Underworld Wisp",
  "폭풍 해파리묘": "Storm Jellycat",
  "로토스 봉오리": "Lotus Bud",
  "동굴 목자묘": "Cave Herder",
  "퍼-씨의 견습묘": "Purr-ce's Apprentice",
  "구혼자 대장": "Suitor Captain",
  "심연 제사묘": "Abyss Priest",
  "캣-립소의 작별 시험": "Cat-lypso's Farewell Trial",
  "포-사이돈의 폭풍 화신": "Paw-seidon's Storm Avatar",
  "망각의 로토스 심장": "Lotus Heart of Oblivion",
  "폴리-먀오무스": "Poly-meow-mus",
  "폭주하는 바람 주머니": "Runaway Bag of Winds",
  "퍼-씨의 거울 환영": "Purr-ce's Mirror Illusion",
  "저승의 봉인문": "Sealed Gate of the Underworld",
  "사이렌 세 자매": "The Three Siren Sisters",
  "스킬라-캣": "Scylla-Cat",
  "카리브디스": "Charybdis",
  "제우-푸스의 심판": "Judgment of Zeu-puss",
  "안티-냐우스": "Anti-nyaus",

  // Routes and stages.
  "오기기아 탈출과 파이아키아 난파": "Escape from Ogygia and Shipwreck at Phaeacia",
  "망각의 로토스 섬": "Island of the Lotus of Oblivion",
  "외눈박이의 동굴": "Cave of the One-Eyed Giant",
  "뮤-올로스의 바람 궁전": "Mew-olus's Palace of Winds",
  "퍼-씨의 마법 정원": "Purr-ce's Enchanted Garden",
  "저승의 기억길": "Path of Underworld Memories",
  "사이렌의 달빛 암초": "Sirens' Moonlit Reef",
  "스킬라·카리브디스 해협": "Strait of Scylla and Charybdis",
  "트리나키아 태양 목장": "Solar Pasture of Thrinacia",
  "이타-캣 귀환과 궁전 탈환": "Return to Itha-Cat and Reclaim the Palace",
  "뗏목을 위한 숲": "Forest for a Raft",
  "파도 앞의 뗏목": "Raft Before the Waves",
  "포-사이돈의 분노": "Wrath of Paw-seidon",
  "달콤한 첫 향기": "The First Sweet Scent",
  "잠든 선원을 깨워라": "Wake the Sleeping Sailor",
  "꿈속의 갈림길": "Fork in the Dream",
  "망각의 심장": "Heart of Oblivion",
  "동굴 입구의 양떼": "Flock at the Cave Mouth",
  "거석이 지나갈 때까지": "Until the Boulder Passes",
  "거석으로 여는 퇴로": "A Retreat Opened by Stone",
  "아무도 아닌 자": "Nobody",
  "폴리-먀오무스의 외눈": "Poly-meow-mus's Eye",
  "바람 궁전의 문": "Gate of the Wind Palace",
  "움직이는 구름문": "Moving Cloud Gates",
  "라이스트리곤 항구": "Laestrygonian Harbor",
  "폭주하는 여덟 바람": "Eight Winds Unbound",
  "아이아이에의 정원문": "Garden Gate of Aeaea",
  "변이 약효를 견뎌라": "Endure the Transformation",
  "거울 회랑 탈출": "Escape the Hall of Mirrors",
  "퍼-씨의 비살상 결투": "Purr-ce's Nonlethal Duel",
  "망자의 강둑": "Bank of the Dead",
  "색이 다른 문": "Gates of Different Colors",
  "어머니의 기억": "A Mother's Memory",
  "티레시아스의 봉인문": "Tiresias's Sealed Gate",
  "첫 번째 노랫결": "First Wave of Song",
  "회전하는 달빛 암초": "Rotating Moonlit Reef",
  "세 수정의 화음": "Harmony of Three Crystals",
  "당기는 물살": "The Pulling Current",
  "좁아지는 안전각": "The Narrowing Safe Angle",
  "스킬라의 앞발": "Scylla's Forepaws",
  "카리브디스의 중심": "Heart of Charybdis",
  "여섯 머리와 검은 소용돌이": "Six Heads and the Black Whirlpool",
  "금빛 목장의 금기": "Taboo of the Golden Pasture",
  "피뢰석의 길": "Path of Lightning Rods",
  "굶주린 선원들의 밤": "Night of the Starving Sailors",
  "거지의 귀환": "The Beggar's Return",
  "방패 진형의 안뜰": "Courtyard of the Shield Formation",
  "열두 도끼의 고리": "Ring of Twelve Axes",
  "궁전의 구혼자들": "The Palace Suitors",
  "안티-냐우스 최후의 연회": "Anti-nyaus's Final Feast",

  // Blessings.
  "아-포-나의 정확한 선": "A-paw-na's True Line",
  "방패 뒤의 해답": "Answer Behind the Shield",
  "첫 충돌의 가호": "Grace of First Contact",
  "고르곤의 시선": "Gorgon's Gaze",
  "완전한 작전": "Perfect Plan",
  "날개 달린 출발": "Winged Start",
  "두 번째 전갈": "Second Message",
  "전령의 지름길": "Messenger's Shortcut",
  "서두르는 회복": "Hastened Recovery",
  "여덟 겹의 항로": "Eightfold Route",
  "따뜻한 햇살": "Warm Sunbeam",
  "태양날의 가장자리": "Edge of the Sunblade",
  "정오의 짧은 그림자": "Noon's Short Shadow",
  "신성한 목장의 맹세": "Oath of the Sacred Pasture",
  "거대한 태양 바퀴": "Great Sun Wheel",
  "뮤-올로스의 순풍": "Mew-olus's Tailwind",
  "봉인된 돌풍": "Sealed Gust",
  "교차하는 바람": "Crosswind",
  "폭풍의 고요한 눈": "Calm Eye of the Storm",
  "모든 바람의 왕": "King of All Winds",
  "몰리 약초": "Moly Herb",
  "거울 속 발톱": "Claw in the Mirror",
  "작아지는 저주": "Shrinking Curse",
  "뒤집히는 약병": "Reversing Vial",
  "거울 궁전": "Palace of Mirrors",
  "캣-립소의 고요한 물": "Cat-lypso's Still Water",
  "불사의 실": "Immortal Thread",
  "오기기아 덩굴": "Vines of Ogygia",
  "일곱 해의 인내": "Seven Years' Patience",
  "죽지 않는 섬": "Undying Island",

  // Relics.
  "이타-캣의 오래된 활": "Old Bow of Itha-Cat",
  "올리브나무 침대 기둥": "Olive-Wood Bedpost",
  "풀리지 않은 수의": "Unfinished Shroud",
  "아르고스의 낡은 목걸이": "Argos's Worn Collar",
  "푸른 여행 망토": "Blue Traveling Cloak",
  "목동의 짧은 울타리": "Herdsman's Low Fence",
  "이타-캣 궁전 열쇠": "Key to the Itha-Cat Palace",
  "외눈박이의 술잔": "One-Eyed Giant's Cup",
  "동굴 숫양의 가죽": "Cave Ram Hide",
  "사이렌의 울림 조개": "Siren Resonance Shell",
  "스킬라의 부러진 이빨": "Scylla's Broken Tooth",
  "소용돌이의 검은 중심": "Black Heart of the Whirlpool",
  "라이스트리곤 투석": "Laestrygonian Throwing Stone",
  "고르곤 방패 문장": "Gorgon Shield Emblem",
  "괴수 부위 도감": "Monster Anatomy Guide",
  "바람 주머니의 매듭": "Knot of the Wind Bag",
  "청동 끝 노": "Bronze-Tipped Oar",
  "파이아키아의 흰 돛": "White Sail of Phaeacia",
  "바다 거품 항아리": "Sea-Foam Jar",
  "폭풍 나침반": "Storm Compass",
  "부러진 돛대 조각": "Broken Mast Fragment",
  "먹물 번진 항로도": "Ink-Stained Route Map",
  "귀향을 가리키는 별": "Homeward Star",
  "몰리의 검은 뿌리": "Black Moly Root",
  "전령의 금빛 깃": "Messenger's Golden Feather",
  "작은 태양 바퀴": "Small Sun Wheel",
  "번개의 파편": "Lightning Fragment",
  "저승길의 동전": "Coin for the Underworld Road",
  "신탁의 창끝": "Oracle Spearhead",
  "오기기아의 은실": "Silver Thread of Ogygia",
  "예언자의 재": "Oracle's Ash",

  // Endgame content.
  "아-포-나의 신탁탑": "A-paw-na's Oracle Tower",
  "신화 괴수 토벌: 스킬라-캣": "Mythic Beast Hunt: Scylla-Cat",
  "갑각과 앞발 파괴": "Break the Carapace and Forepaws",
  "여섯 머리 연쇄 경직": "Stagger All Six Heads in Sequence",
  "동굴 속 본체 마무리": "Finish the Body in the Cave",

  // Material and currency display names.
  "검은 조개껍질": "Black Shell",
  "청동 노 머리": "Bronze Oarhead",
  "캣-립소의 실": "Cat-lypso's Thread",
  "동굴 철광": "Cave Iron",
  "키클롭스 파편": "Cyclops Fragment",
  "앞발 갈고리": "Forepaw Claw",
  "거인의 돌": "Giant's Stone",
  "이타카 청동": "Itha-Cat Bronze",
  "이타카 왕관": "Itha-Cat Crown",
  "연꽃 해독제": "Lotus Antidote",
  "연꽃 섬유": "Lotus Fiber",
  "거울 가루": "Mirror Dust",
  "몰리 꽃": "Moly Flower",
  "몰리 잎": "Moly Leaf",
  "신탁의 가루": "Oracle Dust",
  "신탁 문장": "Oracle Emblem",
  "오기기아 목재": "Ogygian Timber",
  "토벌 비늘": "Raid Scale",
  "숫양 방울": "Ram Bell",
  "유물 가루": "Relic Dust",
  "스킬라 비늘": "Scylla Scale",
  "바다 광석": "Sea Ore",
  "세이렌 진주": "Siren Pearl",
  "태양 방울": "Solar Bell",
  "노래 결정": "Song Crystal",
  "영혼 재": "Spirit Ash",
  "폭풍 추가 출항권": "Extra Storm Sortie",
  "폭풍 유리": "Storm Glass",
  "해협 밧줄": "Strait Rope",
  "태양풀": "Sun Grass",
  "저승의 동전": "Underworld Coin",
  "항해 매듭": "Voyage Knot",
  "밀랍 귀마개": "Wax Earplugs",
  "바람 봉인": "Wind Seal",
  "바람 비단": "Wind Silk",

  // Cutscene episode titles.
  "캣-립소의 섬": "Cat-lypso's Island",
  "뗏목 출항": "Raft Sets Sail",
  "나우시-캣과의 만남": "Meeting Nausi-cat",
  "로토스 먹는 자들의 섬": "Island of the Lotus-Eaters",
  "폴리-머오무스의 동굴": "Poly-meow-mus's Cave",
  "‘아무도 아니다’의 책략": "The ‘Nobody’ Ruse",
  "탈출과 오만한 실수": "Escape and a Proud Mistake",
  "아이올로스의 바람 주머니": "Mew-olus's Bag of Winds",
  "퍼-씨의 마법": "Purr-ce's Magic",
  "1년간의 체류": "A Year-Long Stay",
  "저승 방문": "Journey to the Underworld",
  "사이렌의 노래": "Song of the Sirens",
  "스킬라와 카리브디스": "Scylla and Charybdis",
  "태양신의 소": "Cattle of the Sun God",
  "이타-캣의 숨겨진 집": "The Hidden House of Itha-Cat",
  "아버지와 아들의 재회": "Father and Son Reunited",
  "오랜 친구 아르고스": "Argos, an Old Friend",
  "구혼자들의 모욕": "The Suitors' Insult",
  "활의 시험": "The Trial of the Bow",
  "집이 그를 알아보다": "Home Knows Him",

  // Cutscene subtitles: episodes 1–5.
  "올림포스에서 아-포-나가 제우-푸스에게 간청합니다.\n“먀디세우스를 고향으로 보내 주세요.”": "On Olympus, A-paw-na pleads with Zeu-puss.\n“Please send Meow-dysseus home.”",
  "우레 섞인 구름이 그 간청에 답합니다.": "Thunderous clouds answer her plea.",
  "바닷가의 먀디세우스는 일곱 해 동안\n고향만을 그리며 기다렸습니다.": "By the shore, Meow-dysseus has spent seven years\nwaiting and longing only for home.",
  "캣-립소가 다정히 말을 걸지만,\n그의 시선은 파도 너머에 머뭅니다.": "Cat-lypso speaks to him gently,\nbut his gaze remains beyond the waves.",
  "눈물 한 방울이 흐릅니다.\n“퍼-넬로페가 보고 싶어.”": "A single tear falls.\n“I miss Purr-nelope.”",
  "마침내 희망이 밝아지고,\n허르-먀오스가 해방의 명을 전합니다.": "At last hope brightens,\nand Her-meows brings the order for his release.",
  "신들조차 고향을 향한 그리움을 가둘 수 없습니다.": "Not even the gods can imprison a longing for home.",
  "아침이 오자 그는 뗏목을 만들고,\n기나긴 먀디세이의 항해를 시작합니다.": "At dawn he builds a raft\nand begins the long Meowdyssey home.",

  "작은 발로 모래 위에 뗏목을 짓고,\n먀디세우스는 다시 꿈을 띄웁니다.": "With small paws, Meow-dysseus builds a raft on the sand\nand sets his dream afloat once more.",
  "끝없는 푸른 바다 위에서\n그는 고향을 향해 홀로 길을 잡습니다.": "Across the endless blue sea,\nhe charts a lonely course for home.",
  "그러나 바다에는 주인이 있었습니다.\n분노한 포-세이돈이 폭풍과 함께 솟아오릅니다.": "But the sea has a master.\nAn enraged Paw-seidon rises with the storm.",
  "삼지창이 내려치자 세상은 뒤집히고,\n뗏목과 희망은 거센 파도에 산산이 부서집니다.": "His trident falls and the world turns over;\nraft and hope shatter in the raging waves.",
  "분노를 다 쏟아낸 바다는\n그를 낯선 해안에 토해 냅니다.": "When the sea has spent its fury,\nit casts him onto a strange shore.",
  "쓰러지고 부서졌지만, 아직 살아 있습니다.\n먀디세이는 아직 끝나지 않았습니다.": "Battered and broken, he is still alive.\nThe Meowdyssey is not over yet.",

  "파이아키아의 강가에서 공주 나우시-캣이\n시녀들과 평화롭게 놀고 있었습니다.": "By a Phaeacian river, Princess Nausi-cat\nplays peacefully with her attendants.",
  "그때 수풀 속 바스락거림에\n모두가 숨을 죽입니다.": "Then a rustle in the brush\nmakes everyone hold their breath.",
  "소금과 해초를 뒤집어쓴 먀디세우스가\n난파자의 몰골로 비틀거리며 나타납니다.": "Covered in salt and seaweed, Meow-dysseus\nstaggers out like a shipwrecked ghost.",
  "한때의 왕은 그녀 앞에 엎드려\n말없는 울음으로 자비를 구합니다.": "The once-great king falls before her\nand begs for mercy with wordless tears.",
  "나우시-캣은 괴물이 아니라\n도움이 필요한 이를 보았습니다.": "Nausi-cat sees no monster,\nonly someone in need of help.",
  "그녀가 내민 친절의 발길을 따라\n왕궁과 고향의 희망으로 향합니다.": "He follows the kindness she offers\ntoward the palace and a new hope of home.",

  "파이아키아 왕 앞에서 안전을 얻은 먀디세우스는\n다시 지난 항해를 들려줍니다.": "Safe before the king of Phaeacia, Meow-dysseus\nresumes the tale of his voyage.",
  "바람에 밀린 배는\n로토스 먹는 자들의 섬에 닿았습니다.": "Driven by the wind, the ship\nreached the island of the Lotus-Eaters.",
  "섬사람들이 건넨 달콤한 로토스를 먹자\n선원들의 눈빛이 풀립니다.": "The islanders offer sweet lotus,\nand the sailors' eyes grow distant.",
  "고향도 항해도 잊은 채,\n그들은 이 섬에 영원히 남고 싶어 했습니다.": "Forgetting home and voyage alike,\nthey want to remain on the island forever.",
  "위험을 알아챈 먀디세우스는\n정신 잃은 선원들을 억지로 끌고 갑니다.": "Seeing the danger, Meow-dysseus\ndrags his senseless sailors away by force.",
  "다시는 로토스를 찾지 못하도록\n그들을 노 젓는 자리에 단단히 묶습니다.": "He binds them firmly to their rowing benches\nso they cannot seek the lotus again.",
  "배는 유혹의 섬을 떠나\n다시 거친 바다로 나아갑니다.": "The ship leaves the island of temptation\nand returns to the rough sea.",

  "낯선 섬의 거대한 동굴이\n호기심 많은 발걸음을 기다립니다.": "On a strange island, a vast cave\nwaits for curious paws.",
  "먀디세우스와 선원들은\n돌로 된 입구 안으로 들어갑니다.": "Meow-dysseus and his crew\npass through the stone entrance.",
  "안에는 산더미 같은 치즈와 가축,\n탐나는 물자가 가득했습니다.": "Inside lie mountains of cheese, livestock,\nand stores too tempting to ignore.",
  "선원들은 함정을 느끼고 떠나자 하지만,\n먀디세우스는 주인을 만나려 합니다.": "The crew senses a trap and urges retreat,\nbut Meow-dysseus insists on meeting the owner.",
  "대지가 떨리고 빛이 사라집니다.\n폴리-먀오무스가 돌아왔습니다.": "The ground trembles and the light disappears.\nPoly-meow-mus has returned.",
  "거대한 바위가 굴러와\n동굴은 순식간에 무덤이 됩니다.": "A colossal boulder rolls into place,\nand the cave becomes a tomb.",
  "예의 바른 말에도 거인은 비웃고,\n끔찍한 손길로 선원들을 집어 듭니다.": "The giant mocks every courteous word\nand seizes sailors in his terrible paws.",
  "영웅의 자만은 깊은 슬픔으로 변하고,\n그는 지키지 못한 동료들을 위해 웁니다.": "The hero's pride turns to deep grief,\nand he weeps for the companions he could not save.",
  "공포의 밤이 지나고 새벽이 왔지만,\n구원 대신 더 큰 희생만 남았습니다.": "Dawn follows the night of terror,\nbut it brings more sacrifice, not rescue.",
  "슬픔이 발톱처럼 생각을 벼립니다.\n동굴의 불꽃 속에서 계책이 태어납니다.": "Grief sharpens his thoughts like claws.\nA plan is born in the cave's firelight.",
  "곧 사냥꾼과 먹잇감의 자리가\n뒤바뀔 것입니다.": "Soon hunter and prey\nwill trade places.",

  // Cutscene subtitles: episodes 6–11.
  "거인의 외눈을 향한\n필사의 책략이 시작됩니다.": "A desperate plan against the giant's single eye\nis set in motion.",
  "선원들은 거대한 올리브 나무를 깎아\n날카로운 말뚝을 만듭니다.": "The sailors carve a great olive trunk\ninto a sharpened stake.",
  "말뚝 끝을 불에 달구며\n결행의 순간을 준비합니다.": "They harden its point in the fire\nand prepare for the moment to strike.",
  "먀디세우스는 두려움을 감추고\n폴리-먀오무스에게 독한 술을 권합니다.": "Hiding his fear, Meow-dysseus\noffers Poly-meow-mus potent wine.",
  "술에 취한 거인이 이름을 묻자,\n그는 침착하게 대답합니다.": "When the drunken giant asks his name,\nhe answers calmly.",
  "“내 이름은 아무도 아니다.”\n거인은 어리석은 약속과 함께 웃습니다.": "“My name is Nobody.”\nThe giant laughs and makes a foolish promise.",
  "마침내 거인이 깊이 잠들자\n선원들이 무거운 말뚝을 들어 올립니다.": "At last the giant falls into a deep sleep,\nand the sailors raise the heavy stake.",
  "모두가 힘을 모아\n불에 달군 끝을 외눈에 밀어 넣습니다.": "Together they drive\nthe fire-hardened point into his single eye.",
  "눈먼 거인의 분노에\n동굴 전체가 무섭게 흔들립니다.": "The blinded giant's rage\nshakes the entire cave.",
  "첫 계책은 성공했지만,\n그들은 아직 동굴 안에 갇혀 있습니다.": "The first part of the plan succeeds,\nbut they are still trapped inside the cave.",

  "자만으로 외친 이름 하나가\n바다에 저주를 불러옵니다.": "One name shouted in pride\nsummons a curse upon the sea.",
  "그보다 앞서, 눈먼 거인은\n“아무도”가 자신을 해쳤다고 울부짖었습니다.": "Before that, the blinded giant cried\nthat “Nobody” had harmed him.",
  "동족들은 어리석은 엄살로 여기고\n아무 도움도 주지 않은 채 돌아섭니다.": "His kin dismiss it as foolish whining\nand turn away without helping.",
  "먀디세우스와 선원들은 양의 배 아래 숨어\n들키지 않고 출구로 다가갑니다.": "Meow-dysseus and his crew hide beneath the rams\nand creep unseen toward the exit.",
  "눈먼 발이 바로 곁을 더듬지만,\n모두 숨을 죽이고 공포를 견딥니다.": "Blind paws feel the ground beside them,\nbut they hold their breath and endure the terror.",
  "마침내 햇빛과 짠 바람 속에서\n자유를 되찾습니다.": "At last, in sunlight and salt wind,\nthey regain their freedom.",
  "그러나 안전해지자 오만이 고개를 들고,\n그의 조롱에 거대한 바위가 날아옵니다.": "But once safe, pride rises again,\nand his taunts draw a colossal boulder.",
  "그리고 치명적인 실수.\n먀디세우스는 거인에게 진짜 이름을 밝힙니다.": "Then comes the fatal mistake.\nMeow-dysseus reveals his true name to the giant.",
  "폴리-먀오무스의 기도가 포-세이돈에게 닿고,\n고향으로 가는 길은 폭풍 속으로 멀어집니다.": "Poly-meow-mus's prayer reaches Paw-seidon,\nand the road home recedes into the storm.",

  "봉인된 주머니가 터지며\n사방의 폭풍이 한꺼번에 풀려납니다.": "The sealed bag bursts,\nreleasing every storm at once.",
  "그 전, 먀디세우스 일행은\n바람의 왕 뮤-올로스에게 환대를 받았습니다.": "Before that, Meow-dysseus and his crew\nhad been welcomed by Mew-olus, King of the Winds.",
  "뮤-올로스는 순풍만 남기고\n모든 바람을 가죽 주머니에 봉인해 줍니다.": "Mew-olus leaves only a tailwind free\nand seals every other wind in a leather bag.",
  "아흐레 동안 먀디세우스는 쉬지 않고\n고향을 향해 배를 몰았습니다.": "For nine days Meow-dysseus sails without rest,\nsteering ever closer to home.",
  "이타-캣의 불빛이 보이자\n안도한 그는 마침내 잠에 듭니다.": "When the lights of Itha-Cat appear,\nrelief finally lets him sleep.",
  "선원들은 주머니 안에 보물이 들었다고 의심하고\n질투와 호기심에 매듭을 만집니다.": "The sailors suspect treasure inside the bag\nand touch its knot in jealousy and curiosity.",
  "매듭이 풀리자 갇혀 있던 바람이\n무서운 포효와 함께 터져 나옵니다.": "The knot comes loose, and the captive winds\nerupt with a terrible roar.",
  "배는 거대한 파도에 휩쓸리고,\n눈앞의 고향은 다시 멀어집니다.": "The ship is swept away by enormous waves,\nand the home before their eyes grows distant again.",
  "폭풍은 일행을 뮤-올로스의 섬으로\n되돌려 보냅니다.": "The storm hurls them back\nto Mew-olus's island.",
  "신들의 저주라 여긴 바람의 왕은\n차갑게 그들을 내쫓습니다.": "Believing them cursed by the gods,\nthe King of the Winds coldly casts them out.",

  "다정한 미소와 잔혹한 주문.\n친구들이 한순간에 짐승으로 변합니다.": "A gentle smile and a cruel spell.\nIn an instant, his friends become beasts.",
  "거짓된 푸름으로 뒤덮인 섬,\n안개 속에는 퍼-씨의 궁전이 기다립니다.": "On an island wrapped in deceptive green,\nPurr-ce's palace waits in the mist.",
  "황금 그릇의 달콤한 음식은 저주였고,\n허기는 선원들을 방심하게 했습니다.": "The sweet food in golden bowls was a curse,\nand hunger lowered the sailors' guard.",
  "에우릴로코스만이 우리를 빠져나와\n끔찍한 소식을 선장에게 전합니다.": "Only Eurylochus escapes the trap\nand brings the dreadful news to his captain.",
  "먀디세우스의 슬픔은 강철 같은 결의가 됩니다.\n그는 동료들을 버리지 않습니다.": "Meow-dysseus's grief hardens into steel.\nHe will not abandon his companions.",
  "그때 허르-먀오스가 나타나\n마법을 막아 줄 빛나는 약초를 건넵니다.": "Then Her-meows appears\nand gives him a shining herb that wards off magic.",
  "먀디세우스는 독을 마시고도 버텨 내며\n퍼-씨의 주문을 깨뜨립니다.": "Meow-dysseus drinks the poison and endures,\nbreaking Purr-ce's spell.",
  "영웅의 의지가 저주를 되돌리고,\n잃었던 동료들은 다시 고양이로 돌아옵니다.": "The hero's will reverses the curse,\nand his lost companions become cats once more.",

  "앞을 알 수 없는 길 앞에서\n영웅의 마음에도 두려움이 번집니다.": "Before a road whose end he cannot see,\nfear spreads even through the hero's heart.",
  "그러나 먼저 퍼-씨는 마법을 거두어\n선원들을 본래 모습으로 돌려놓습니다.": "But first Purr-ce lifts her magic\nand restores the sailors to their true forms.",
  "햇살과 연회, 포근한 낮잠 속에서\n일 년이 흐르고 이타-캣은 잊힌 꿈이 됩니다.": "Amid sunlight, feasts, and warm naps,\na year passes and Itha-Cat becomes a fading dream.",
  "안락함은 비단처럼 따뜻한 감옥.\n한 충직한 목소리가 귀향을 다시 일깨웁니다.": "Comfort is a prison lined with warm silk.\nOne faithful voice awakens the call of home again.",
  "방패에 비친 자신을 바라보며\n먀디세우스의 영웅다운 마음이 깨어납니다.": "Seeing himself reflected in a shield,\nMeow-dysseus's heroic spirit wakes.",
  "그러나 퍼-씨가 차가운 진실을 전합니다.\n먼저 죽은 자들의 땅으로 가야 합니다.": "Then Purr-ce delivers a cold truth.\nFirst he must travel to the land of the dead.",
  "새벽을 찾으려면\n먼저 그림자의 나라를 지나야 합니다.": "To find the dawn,\nhe must first cross the realm of shadows.",
  "예언의 무게에\n왕의 마음마저 무너져 내립니다.": "Under the weight of prophecy,\neven a king's heart gives way.",
  "일행은 빛나는 섬을 뒤로하고\n어둠과 폭풍을 향해 다시 출항합니다.": "The crew leaves the shining island behind\nand sails once more toward darkness and storm.",

  "기억을 품으려 손을 뻗지만,\n아들은 어머니의 영혼을 안을 수 없습니다.": "A son reaches out to embrace a memory,\nbut he cannot hold his mother's spirit.",
  "일행은 태양조차 닿지 않는\n세상 끝의 쓸쓸한 해안에 도착합니다.": "The crew reaches a desolate shore at the world's end,\nwhere even sunlight cannot reach.",
  "먀디세우스가 검은 땅에 제물을 붓고\n말없는 영혼들을 부릅니다.": "Meow-dysseus pours an offering onto the black earth\nand calls to the silent dead.",
  "잊힌 울음의 물결처럼\n수많은 망령이 산 자를 향해 떠오릅니다.": "Like a tide of forgotten cries,\ncountless shades rise toward the living.",
  "눈 없이도 운명의 실을 보는 예언자,\n티레시아스가 다가옵니다.": "Tiresias approaches, a prophet\nwho sees the threads of fate without eyes.",
  "그는 신의 분노를 경고합니다.\n태양신의 소에는 절대 손대지 말라.": "He warns of divine wrath.\nNever touch the Sun God's cattle.",
  "그때 먀디세우스는\n사랑의 흔적으로 남은 어머니를 발견합니다.": "Then Meow-dysseus sees his mother,\nremaining only as a trace of love.",
  "손은 허공을 지나가고,\n느낄 수 없는 온기를 위해 눈물이 흐릅니다.": "His paws pass through empty air,\nand tears fall for a warmth he cannot feel.",
  "어머니는 고향 궁전을 차지한 구혼자들과\n기다리는 왕국의 소식을 전합니다.": "His mother tells him of the suitors occupying his palace\nand the kingdom still waiting for him.",
  "그는 그림자를 등지고 돌아섭니다.\n슬픔은 귀향을 향한 결의의 칼이 됩니다.": "He turns his back on the shadows.\nGrief becomes a blade of resolve pointed homeward.",

  // Cutscene subtitles: episodes 12–14. These follow the approved English
  // narration while normalizing every visible name to the character bible.
  "그림자의 땅을 지난 뒤 모든\n파도는 하나의 경고를 실어 왔다.": "After the land of shadows, every\nwave carried a warning.",
  "퍼-씨는 경고했다.": "Purr-ce warned him.",
  "그 노래를 꼭 들어야 한다면, 먼저 몸을 묶으라고.": "If you must hear them, bind yourself first.",
  "유혹을 이기는 첫 번째 방법은\n자기 자신을 믿지 않는 것이다.": "The first way to defeat temptation\nis to stop trusting yourself.",
  "선원들이 살아남으려면 오직 한 가지,\n그 노래를 결코 듣지 말아야 했다.": "The crew could survive only if\nthey never heard the song.",
  "내가 애원하더라도 더 단단히 묶어라.": "Even if I beg, tie me tighter.",
  "안개 너머에서 사이렌 고양이들이 노래하기 시작했다.": "Out of the fog, the Siren Cats began to sing.",
  "그 노래는 그의 슬픔을 진짜 이름으로 불렀다.": "Their song called his sorrow by its true name.",
  "가장 지혜로운 고양이도 아직 애원했다.": "The wisest cat alive still begged",
  "자신을 파멸시킬 바로 그것을 달라고.": "for the very thing that would destroy him.",
  "그들은 노래를 이긴 것이 아니었다.": "They did not defeat the song.",
  "끝까지 버텼을 뿐이다.": "They outlasted it.",
  "그러나 안개 너머엔 기다리고 있었다.": "But beyond the fog waited",
  "안전한 쪽이 없는 선택이.": "a choice with no safe side.",

  "사이렌을 벗어난 뒤, 바다는 자비\n대신 더 좁은 선택만을 내밀었습니다.": "After the Sirens, the sea offered\nno mercy, only a narrower choice.",
  "한쪽에는 배 전체를 삼키려는\n카리브디스가 기다리고 있었습니다.": "On one side, Charybdis waited\nto swallow the whole ship.",
  "다른 쪽 절벽에서는 스킬라가 지켜보고 있었습니다.": "On the other, Scylla watched from the cliff.",
  "먀디세우스는 모두를 죽이지는 않을 상처를 택했습니다.": "Meow-dysseus chose the wound that would not kill them all.",
  "그는 그래도 무장했지만, 용기만으로는\n닿을 수 없는 높이였습니다.": "He armed himself anyway, though courage\ncould not reach high enough.",
  "동굴에서 굶주린 여섯 머리가\n안개 속으로 몸을 내밀었습니다.": "From the cave, six hungry heads\nleaned into the mist.",
  "소용돌이는 모두를 뜻했기에, 배는\n절벽 가까이 기어가듯 나아갔습니다.": "The ship crept close to the cliff\nbecause the whirlpool meant everyone.",
  "스킬라는 선원 여섯을 낚아챘고,\n영웅은 허공만 내리칠 수 있었습니다.": "Scylla took six sailors, and the hero\ncould only strike at empty air.",
  "그들은 승리 없이 빠져나왔습니다.": "They escaped without victory.",
  "모든 생존이 승리처럼 느껴지는 것은 아닙니다.": "Not every survival feels like winning.",

  "번개가 떨어진 뒤, 바다 위에는\n먀디세우스만 남았습니다.": "After the lightning, only Meow-dysseus\nremained on the sea.",
  "이 벌은 태양신의 섬에서 시작됐습니다.": "This punishment began on the Sun God's island.",
  "그 섬에는 절대 건드리면 안\n되는 신성한 소들이 있었죠.": "Its sacred cattle were never\nto be touched.",
  "먀디세우스는 선원들에게 경고했습니다.\n배가 고파도 저 소만은 안 된다고요.": "Meow-dysseus warned his crew.\nHunger changed nothing: the cattle were forbidden.",
  "하지만 폭풍은 길어지고, 남은 식량은 바닥났습니다.": "But the storm dragged on, and every basket stood empty.",
  "결국 선원들은 몰래 금기를 어기고 맙니다.": "At last the starving crew broke the taboo in secret.",
  "불씨와 태양 목걸이만이, 그들이\n넘은 선을 보여줬습니다.": "Only embers and a fallen sun collar\nrevealed the line they had crossed.",
  "뒤늦게 돌아온 먀디세우스는 모든 것을 알아차립니다.": "One glance told the returning Meow-dysseus everything.",
  "도망치듯 바다로 나섰지만, 하늘은\n이미 심판을 준비하고 있었습니다.": "They fled to sea, but the sky\nhad already prepared its judgment.",
  "제우-푸스의 번개가 배를 갈랐고,\n선원들은 파도 속으로 사라졌습니다.": "Zeu-puss split the ship with lightning,\nand every sailor vanished beneath the waves.",
  "그리고 마지막에 남은 것은, 부서진\n나무를 붙든 먀디세우스뿐이었습니다.": "In the end, only Meow-dysseus remained,\nclinging to broken wreckage.",
  "금기를 어긴 대가는 늦게 와도,\n결코 길을 잃지 않습니다.": "The price of a broken taboo may come late,\nbut it never loses its way.",

  // Cutscene subtitles: episodes 15–17.
  "태양신의 벌 뒤, 배는 사라지고\n먀디세우스만 살아남았습니다.": "After the Sun God's punishment, the ship was gone\nand only Meow-dysseus survived.",
  "파도는 그를 캣-립소의 섬, 오기기아로 밀어 올렸죠.": "The waves carried him to Ogygia, Cat-lypso's island.",
  "그곳에서 7년. 그는 매일 바다\n너머 고향을 그리워했습니다.": "Seven years passed there. Every day he longed\nfor home beyond the sea.",
  "마침내 뗏목을 만들고, 집으로\n가는 바다에 몸을 맡깁니다.": "At last he built a raft\nand entrusted himself to the sea leading home.",
  "긴 모험담을 들은 파이아키아 고양이들은\n그를 집으로 보내기로 합니다.": "After hearing his long tale, the Phaeacian cats\nchose to carry him home.",
  "그들은 잠든 영웅을 이타-캣\n해안에 조용히 내려놓았습니다.": "They quietly left the sleeping hero\non the shore of Itha-Cat.",
  "하지만 도움에는 대가가 따랐습니다.\n돌아가던 배는 항구 앞에서 돌이 됩니다.": "But their help carried a price.\nTheir returning ship turned to stone before the harbor.",
  "눈을 뜬 먀디세우스는 고향을 알아보지 못합니다.\n아-포-나가 안개로 숨겼기 때문이죠.": "Meow-dysseus woke unable to recognize his home.\nA-paw-na had hidden it in mist.",
  "그는 먼저 선물과 보물을 세었습니다.\n믿음보다 생존이 앞섰습니다.": "He counted every gift and treasure first.\nSurvival came before trust.",
  "그때 한 목동 고양이가 다가와\n묻습니다. \"너는 누구냐?\"": "Then a shepherd cat approached\nand asked, “Who are you?”",
  "먀디세우스는 이름을 숨기고, 낯선\n여행자인 척 이야기를 꾸며냅니다.": "Meow-dysseus hid his name\nand invented the tale of a foreign traveler.",
  "그러자 목동의 모습이 사라지고, 아-포-나가\n안개를 걷습니다. 여기가 바로 이타-캣입니다.": "The shepherd's guise vanished, and A-paw-na\nlifted the mist. This was Itha-Cat.",
  "하지만 집은 안전하지 않았습니다. 궁전에는\n구혼자들이 그의 자리를 빼앗고 있었습니다.": "But home was not safe. In the palace,\nsuitors had stolen his place.",
  "아-포-나는 그를 늙은 거지로 바꿉니다.\n진짜 이름을 되찾기 전까지 숨기 위해서요.": "A-paw-na turned him into an old beggar,\nhidden until he could reclaim his true name.",
  "집에 도착했습니다. 이제 그는, 알려지기\n전에 먼저 기다리는 법을 배워야 합니다.": "He was home. Now he had to learn to wait\nbefore letting himself be known.",

  "변장한 먀디세우스는 충직한 돼지치기\n유-먀오스의 오두막에 닿았습니다.": "Disguised, Meow-dysseus reached the hut\nof faithful swineherd Eumaeus.",
  "유-먀오스는 주인을 알아보지 못했지만, 낯선\n거지에게도 불과 잠자리를 내주었습니다.": "Eumaeus did not recognize his master, but still\noffered a strange beggar fire and a bed.",
  "그때 텔레-묘-쿠스도 구혼자들의 매복을\n피해 이타-캣으로 돌아오고 있었습니다.": "Meanwhile, Tele-meow-chus was returning to Itha-Cat,\nhaving slipped past the suitors' ambush.",
  "젊은 왕자가 오두막 문에 서자, 유-먀오스는\n살아 돌아온 가족을 보듯 달려 나갔습니다.": "When the young prince reached the hut, Eumaeus\nran to him as if family had returned from the dead.",
  "그러나 난롯가의 거지는 숨을 삼켰습니다. 바로\n앞에 아들이 있었지만 아직 말할 수 없었습니다.": "By the hearth, the beggar held his breath. His son\nstood before him, but he could not speak yet.",
  "유-먀오스가 퍼-넬로페에게 소식을 전하러\n떠나자, 오두막에는 아버지와 아들만 남았습니다.": "When Eumaeus left to bring Purr-nelope the news,\nfather and son were alone in the hut.",
  "그 순간 아-포-나가 나타나 낡은\n후드와 거지의 먼지를 걷어 냈습니다.": "Then A-paw-na appeared and lifted away\nthe ragged hood and beggar's dust.",
  "텔레-묘-쿠스는 뒤로 물러섰습니다. 방금\n전의 거지가 신처럼 변해 있었기 때문입니다.": "Tele-meow-chus stepped back. The beggar before him\nnow seemed divine.",
  "먀디세우스는 낮게 말했습니다. \"신이\n아니다. 나는 네 아버지다.\"": "Meow-dysseus spoke softly. “I am no god.\nI am your father.”",
  "스무 해의 빈자리가 무너졌고,\n둘은 서로를 끌어안았습니다.": "Twenty empty years gave way,\nand they embraced.",
  "하지만 눈물 뒤에는 계획이 필요했습니다.": "But after the tears, they needed a plan.",
  "둘은 무기를 숨기고, 구혼자들을 세고,\n누구에게도 진실을 말하지 않기로 했습니다.": "They hid weapons, counted the suitors,\nand agreed to tell no one the truth.",
  "궁전의 적들은 매복 실패를 알고 다시 이를 갈았습니다.": "At the palace, their enemies learned the ambush had failed and seethed anew.",
  "왕국을 되찾기 전에, 그는 먼저 아들을 되찾았습니다.": "Before reclaiming his kingdom, he reclaimed his son.",

  "텔레-묘-쿠스는 계획대로 먼저 궁전으로 돌아갔습니다.": "As planned, Tele-meow-chus returned to the palace first.",
  "퍼-넬로페는 아들이 무사하다는 사실에 안도했지만,\n그는 아직 모든 진실을 말할 수 없었습니다.": "Purr-nelope rejoiced to see her son safe,\nthough he could not tell her everything yet.",
  "그 사이 유-먀오스는 거지로 변장한\n먀디세우스를 데리고 도시로 향했습니다.": "Meanwhile, Eumaeus led the beggar-disguised\nMeow-dysseus toward the city.",
  "길 위에서 무례한 염소치기가 늙은 거지를\n비웃었지만, 먀디세우스는 분노를 삼켰습니다.": "On the road, a rude goatherd mocked the old beggar,\nbut Meow-dysseus swallowed his anger.",
  "궁전 문 앞에는 잊힌 늙은 친구가 누워 있었습니다.": "At the palace gate lay an old friend everyone had forgotten.",
  "그는 아르고스, 스무 해 동안 주인을\n기다린 오래된 궁전 고양이였습니다.": "He was Argos, the old palace cat\nwho had waited twenty years for his master.",
  "누구도 누더기 속의 왕을 알아보지\n못했지만, 아르고스만은 알아보았습니다.": "No one recognized the king beneath the rags,\nbut Argos knew him.",
  "먀디세우스는 눈물을 들키지 않으려고\n후드 아래로 얼굴을 돌렸습니다.": "Meow-dysseus turned his face beneath the hood\nto hide his tears.",
  "유-먀오스는 그저, 이 늙은 친구가 먼 곳에서\n사라진 주인의 고양이였다고 말했습니다.": "Eumaeus only said the old cat belonged\nto a master lost far away.",
  "주인을 한 번 더 알아본 뒤,\n아르고스는 조용히 눈을 감았습니다.": "After recognizing his master one last time,\nArgos quietly closed his eyes.",
  "그리고 먀디세우스는 거지의 모습으로\n자기 집 문턱을 넘었습니다.": "Then Meow-dysseus crossed the threshold\nof his own home in a beggar's guise.",
  "모두가 그를 몰랐지만, 가장 오래\n기다린 친구만은 알아보았습니다.": "No one else knew him, but the friend\nwho had waited longest did.",

  // Cutscene subtitles: episodes 18–20.
  "아르고스의 문턱을 지나, 먀디세우스는\n거지의 후드로 자기 집에 들어섰습니다.": "Past Argos, Meow-dysseus entered his own home\nbeneath the beggar's hood.",
  "안에서는 구혼자들이 남의 식탁을\n자기 왕좌처럼 차지하고 있었습니다.": "Inside, the suitors had made another cat's table\ninto their throne.",
  "그는 작은 그릇을 들고 한 마리씩 지나갔습니다.": "Carrying a small bowl, he passed them one by one.",
  "누가 조금이라도 나누는지, 누가 웃음으로\n마음을 드러내는지 보려는 시험이었습니다.": "It was a test of who would share even a little\nand who would reveal their heart through laughter.",
  "그중 안티-냐우스는 빈손보다\n더 모진 것을 내밀었습니다.": "Anti-nyaus offered him something\ncrueler than an empty paw.",
  "안티-냐우스는 발밑의 낮은 걸상을 집어 던졌습니다.": "Anti-nyaus snatched up the low footstool at his feet and threw it.",
  "낮은 걸상이 어깨를 스쳤지만, 먀디세우스는\n지팡이를 쥔 채 움직이지 않았습니다.": "The footstool struck his shoulder, but Meow-dysseus\ngripped his staff and did not move.",
  "텔레-묘-쿠스의 몸이 먼저 일어나려 했습니다.": "Tele-meow-chus began to rise.",
  "그러나 후드 아래의 한 번의\n눈빛이 아들을 멈춰 세웠습니다.": "But one glance from beneath the hood\nstopped his son.",
  "위층의 퍼-넬로페는 그 소식을\n듣고 낯선 거지를 바라보았습니다.": "Upstairs, Purr-nelope heard the news\nand studied the strange beggar.",
  "그는 많은 것을 잃은 여행자처럼\n말했지만, 자신의 이름만은 숨겼습니다.": "He spoke like a traveler who had lost much,\nyet guarded his own name.",
  "밤이 깊어도 궁전의 웃음은 멈추지 않았습니다.": "Even deep into the night, the palace laughter continued.",
  "먀디세우스는 고개를 낮춘 채, 누가\n죄를 쌓는지 끝까지 지켜보았습니다.": "Meow-dysseus kept his head bowed and watched\nto the end as each cat added to their guilt.",
  "그는 바다를 건너 싸우러 왔지만,\n이제는 기다림으로 이겨야 했습니다.": "He had crossed the sea to fight;\nnow he had to win by waiting.",

  "새벽, 퍼-넬로페는 오래 잠겨 있던 활을 꺼냈습니다.": "At dawn, Purr-nelope brought out the long-locked bow.",
  "그 활을 당기고 열두 도끼의 구멍을\n통과시키는 자와 혼인하겠다고 말했습니다.": "She would marry the cat who could string it\nand shoot through the holes of twelve axes.",
  "텔레-묘-쿠스가 먼저 도끼를\n세우고 활을 들어 보았습니다.": "Tele-meow-chus set the axes first\nand took up the bow.",
  "그는 거의 성공할 뻔했지만, 아버지의\n작은 눈빛을 보고 멈추었습니다.": "He nearly succeeded, but stopped\nat a subtle signal from his father.",
  "구혼자들은 차례로 활을 잡았지만,\n누구도 시위를 걸지 못했습니다.": "The suitors took the bow in turn,\nbut none could string it.",
  "안티-냐우스는 활을 불 곁에 데우며 시간을 끌었습니다.": "Anti-nyaus stalled by warming the bow beside the fire.",
  "그때 거지 차림의 먀디세우스가 조용히 말했습니다.": "Then Meow-dysseus, dressed as a beggar, spoke quietly.",
  "자신도 한번 잡아 보게 해 달라고요.": "He asked to hold it once himself.",
  "웃음이 궁전을 가득 채웠지만, 퍼-넬로페는\n그에게 기회를 주라 했습니다.": "Laughter filled the palace, but Purr-nelope\nordered them to give him a chance.",
  "텔레-묘-쿠스는 어머니를 위층으로 모시고,\n충성스러운 손들이 문을 닫았습니다.": "Tele-meow-chus led his mother upstairs,\nwhile loyal paws closed the doors.",
  "활은 이상할 만큼 가볍게 그의 발 사이에서 휘었습니다.": "In his paws, the bow bent with uncanny ease.",
  "화살은 열두 도끼 사이를 한 줄로 지나갔습니다.": "The arrow flew in one line through all twelve axes.",
  "그리고 궁전의 웃음이 멈췄습니다.": "Then the palace laughter stopped.",
  "활은 궁전보다 먼저 자기 주인을 기억했습니다.": "The bow remembered its master before the palace did.",

  "화살이 열두 도끼를 지나자, 궁전의\n웃음은 한순간에 멈췄습니다.": "When the arrow crossed twelve axes,\nthe palace laughter stopped in an instant.",
  "먀디세우스는 더 이상 숨지 않았습니다.\n문턱에 서서 자기 이름을 밝혔습니다.": "Meow-dysseus hid no longer.\nAt the threshold, he reclaimed his name.",
  "닫힌 문 앞에서 구혼자들은 처음으로\n자신들이 빼앗은 집의 무게를 느꼈습니다.": "Before the barred doors, the suitors finally felt\nthe weight of the home they had stolen.",
  "텔레-묘-쿠스와 충성스러운 손들이 그의 곁에\n섰고, 가족의 집은 다시 하나로 모였습니다.": "Tele-meow-chus and loyal paws stood beside him,\nand the broken family became one again.",
  "아-포-나의 빛은 그들을 대신해 싸우지\n않았습니다. 다만 끝까지 설 용기를 비추었습니다.": "A-paw-na's light did not fight in their place.\nIt showed them the courage to stand to the end.",
  "그날, 구혼자들의 오만은 단단히 꺾였습니다.": "That day, the suitors' pride was utterly broken.",
  "궁전이 조용해지자, 먀디세우스는\n분노보다 질서를 먼저 세웠습니다.": "When the palace grew quiet, Meow-dysseus\nchose order before anger.",
  "그러나 퍼-넬로페는 쉽게 믿지 않았습니다.\n기다린 세월이 길수록 확인도 깊어야 했습니다.": "Yet Purr-nelope would not believe at once.\nYears of waiting demanded deeper proof.",
  "그녀는 침대를 옮기라 했고, 먀디세우스는 그\n침대가 움직일 수 없다는 비밀을 말했습니다.": "She ordered their bed moved, and Meow-dysseus\nrevealed why it could never move.",
  "살아 있는 캣닢 나무로 만든 침대. 그 기억\n앞에서, 집은 마침내 그를 알아보았습니다.": "A bed built around a living catnip tree.\nBefore that memory, home knew him at last.",

  // Story interludes.
  "항로 07 · 예언 뒤의 항해": "Route 07 · Voyage Beyond the Prophecy",
  "노래 앞의 맹세": "An Oath Before the Song",
  "저승에서 돌아온 먀디세우스는 퍼-씨의 섬에서 예언과 앞으로의 위험을 다시 확인했다.": "After returning from the Underworld, Meow-dysseus revisited Purr-ce's island to hear the prophecy and the dangers ahead once more.",
  "선원들은 밀랍으로 귀를 막고, 선장은 노래를 듣되 돛대의 밧줄을 풀지 말라고 명했다.": "The crew stopped their ears with wax, while their captain ordered them not to loosen his ropes from the mast, no matter what the song made him say.",
  "항로 08 · 노래가 멎은 뒤": "Route 08 · After the Song Fell Silent",
  "두 재앙 사이의 길": "The Path Between Two Disasters",
  "사이렌의 노랫결을 벗어난 배 앞에 스킬라와 카리브디스가 지키는 좁은 해협이 나타났다.": "Beyond the Sirens' song, the ship reached a narrow strait guarded by Scylla and Charybdis.",
  "모두를 구할 길은 없었다. 먀디세우스는 배 전체를 삼킬 소용돌이를 피해 절벽 쪽 항로를 택했다.": "There was no path that could save everyone. Meow-dysseus steered toward the cliff to avoid the whirlpool that would swallow the entire ship.",
  "항로 09 · 해협의 대가": "Route 09 · The Price of the Strait",
  "태양 목장의 금기": "The Taboo of the Sun God's Pasture",
  "해협에서 여섯 동료를 잃은 배는 마침내 헬리-포스의 소들이 사는 트리나키아에 닿았다.": "After losing six companions in the strait, the ship finally reached Thrinacia, home to Heli-paws's sacred cattle.",
  "티레시아스의 경고는 분명했다. 아무리 굶주려도 신성한 소만은 건드려서는 안 된다.": "Tiresias's warning was clear: however hungry they became, they must never touch the sacred cattle.",
  "회상 막간 · 폭풍 뒤의 세월": "Memory Interlude · The Years After the Storm",
  "난파 뒤, 홀로": "Alone After the Wreck",
  "제우-푸스의 번개가 배를 산산이 흩뜨렸고, 먀디세우스만 부서진 돛대에 매달려 살아남았다.": "Zeu-puss's lightning shattered the ship, and only Meow-dysseus survived, clinging to the broken mast.",
  "그는 다시 소용돌이를 지나 긴 표류 끝에 오기기아에 닿았고, 그곳에서 일곱 해를 보내게 되었다.": "He passed the whirlpool once more and, after a long drift, reached Ogygia, where he would spend seven years.",
  "항로 10 · 회상의 끝": "Route 10 · The End of the Recollection",
  "파이아키아에서 이타-캣으로": "From Phaeacia to Itha-Cat",
  "트리나키아의 이야기가 끝나자 파이아키아 궁정의 회상도 현재로 돌아왔다.": "As the tale of Thrinacia ended, the Phaeacian court returned from memory to the present.",
  "사람들은 홀로 남은 영웅의 귀향을 도왔고, 배는 잠든 먀디세우스를 마침내 이타-캣 해안에 내려놓았다.": "The Phaeacians helped the lone hero home, and their ship finally set the sleeping Meow-dysseus on the shore of Itha-Cat.",
  "아-포-나는 왕궁을 되찾을 때까지 정체를 숨기라며 그를 늙은 떠돌이 고양이 모습으로 바꾸었다.": "A-paw-na changed him into an old wandering cat and told him to hide his identity until the palace was his again.",
  "귀향 막간 · 숨겨진 왕": "Homecoming Interlude · The Hidden King",
  "충직한 목자의 오두막": "The Faithful Swineherd's Hut",
  "변장한 먀디세우스는 먼저 충직한 유-먀오스의 오두막으로 향했다.": "Disguised, Meow-dysseus first made his way to the hut of faithful Eumaeus.",
  "왕궁에 들어가기 전, 살아남은 벗과 아들 텔레-묘-쿠스를 찾아 구혼자들의 수를 살펴야 했다.": "Before entering the palace, he had to find his surviving allies and his son, Tele-meow-chus, then learn the suitors' numbers.",
  "귀향 종장 · 흔들리지 않는 약속": "Homecoming Finale · An Unshaken Promise",
  "마침내, 집으로": "Home at Last",
  "구혼자들의 오만이 꺾인 뒤에도 퍼-넬로페는 마지막으로 둘만 아는 침상의 비밀을 물었다.": "Even after the suitors' pride was broken, Purr-nelope asked one final question about the bed whose secret only they knew.",
  "먀디세우스가 변함없는 답을 들려주자 오랜 기다림은 끝났고, 가족은 마침내 서로를 알아보았다.": "When Meow-dysseus gave the answer that had never changed, the long wait ended and the family finally recognized one another.",
});

export const CONTENT_ENGLISH_RULES: readonly TranslationRule[] = Object.freeze([
  {
    pattern: /^(.+) ×([\d,]+)$/u,
    replacement: (_match, name, amount) => `${CONTENT_ENGLISH_CATALOG[name] ?? name} ×${amount}`,
  },
]);
