import type { EnglishCatalog, TranslationRule } from "../catalogTypes";

/**
 * Shared shell, navigation, settings, and platform copy.
 *
 * Korean remains the canonical source language. English values intentionally
 * live here so terminology can be reviewed without walking scene code.
 */
export const CORE_ENGLISH_CATALOG: EnglishCatalog = Object.freeze({
  "고양이 오디세이": "Cat Odyssey",
  "고양이 오디세이 게임": "Cat Odyssey game",
  "항해 준비에 실패했습니다": "Failed to prepare the voyage",
  "설정 · 도움말": "Settings & Help",
  "항해 환경": "Voyage Settings",
  "소리·조작·표시 방식을 언제든 안전하게 바꿀 수 있습니다.": "Change audio, controls, and display options at any time.",
  "진행 데이터 초기화": "Reset Progress",
  "학습으로 얻은 다이아 잔액은 초기화되지 않습니다": "Diamonds earned through learning will not be reset.",
  "설정 완료": "Done",
  "소리": "Audio",
  "각 음량은 전체 음량과 곱해져 적용됩니다.": "Each channel is multiplied by the master volume.",
  "전체 음량": "Master Volume",
  "배경 음악": "Music",
  "효과음": "Sound Effects",
  "전투 도움말 다시 보기": "Review Combat Help",
  "조준 취소 · 우정 연계 · 적 예고 · 해역 목표": "Cancel aim · Friendship combos · Enemy warnings · Objectives",
  "컷신 언어는 영상 아래 자막에만 적용되며, 게임 진행과 보상에는 영향을 주지 않습니다.": "Language applies to cutscene subtitles and does not affect progress or rewards.",
  "조작과 화면": "Controls & Display",
  "모션 줄이기": "Reduce Motion",
  "화면 이동과 반복 애니메이션을 최소화": "Minimize camera movement and looping animation",
  "화면 흔들림": "Screen Shake",
  "모션 줄이기 설정으로 현재 비활성": "Disabled while Reduce Motion is on",
  "강한 타격의 카메라 반응": "Camera response to heavy impacts",
  "조준 보조": "Aim Assist",
  "첫 반사까지 예상 궤적 표시": "Show the predicted path through the first ricochet",
  "읽기와 색상 구분": "Text & Color",
  "글자 크기": "Text Size",
  "공용 UI·도감·전투 핵심 정보": "Menus, collection, and key battle information",
  "고대비 표시": "High Contrast",
  "더 굵은 윤곽선과 밝은 경고": "Heavier outlines and brighter warnings",
  "색각 구분": "Color Differentiation",
  "색뿐 아니라 아이콘과 선 모양도 변경": "Also changes icons and line patterns",
  "켜짐": "On",
  "꺼짐": "Off",
  "비활성": "Disabled",
  "보통 100%": "Standard 100%",
  "크게 115%": "Large 115%",
  "기본 색상": "Default Colors",
  "적록 구분": "Deuteranopia",
  "청황 구분": "Tritanopia",
  "게임 언어 · 자막": "Game Language & Subtitles",
  "컷신 언어 · 자막": "Game Language & Subtitles",
  "한국어 UI와 한국어 컷신 자막": "Korean interface and Korean cutscene subtitles",
  "원본 영상 아래에 한국어 자막 표시": "Korean interface and Korean cutscene subtitles",
  "English UI and accurate English cutscene subtitles": "English UI and accurate English cutscene subtitles",
  "영상에 포함된 English captions 사용": "English interface and accurate English cutscene subtitles",
  "한국어": "한국어",
  "전투에서는 원형·파선·마름모·경고 무늬가 색상과 함께 표시됩니다.": "Battles pair colors with circles, dashed lines, diamonds, and warning patterns.",
  "● 아군": "● Ally",
  "× 적": "× Enemy",
  "◆ 목표": "◆ Objective",
  "⚠ 위험": "⚠ Danger",
  "전투 도움말": "Combat Help",
  "필요할 때만 펼쳐 보는 핵심 규칙 · 진행도와 코치마크는 초기화되지 않습니다": "Open these key rules whenever needed. Progress and coach marks are unchanged.",
  "당기기·취소 연습 다시 보기": "Replay Aim & Cancel Practice",
  "우클릭 · Esc · 두 번째 손가락 탭": "Right-click · Esc · second-finger tap",
  "도움말 닫기": "Close Help",
  "설정을 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.": "Could not save settings. Please try again shortly.",
  "언어 설정을 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.": "Could not save the language setting. Please try again shortly.",
  "글자 크기 설정": "text size setting",
  "고대비 설정": "high-contrast setting",
  "색각 구분 설정": "color differentiation setting",
  "모든 진행 데이터를 초기화할까요?": "Reset all progress data?",
  "스토리, 영웅, 장비, 재료와 설정이 처음 상태로 돌아갑니다. 학습으로 얻은 다이아 잔액은 유지됩니다.": "Story, heroes, equipment, materials, and settings will return to their initial state. Diamonds earned through learning are kept.",
  "스토리, 영웅, 장비, 재료와 설정이 처음 상태로 돌아갑니다. 언어 선택과 학습으로 얻은 다이아 잔액은 유지됩니다.": "Story, heroes, equipment, materials, and settings will return to their initial state. Your language choice and Diamonds earned through learning are kept.",
  "진행 데이터를 초기화하지 못했습니다. 잠시 후 다시 시도해 주세요.": "Could not reset progress. Please try again shortly.",
  "다이아 사용 확인": "Confirm Diamond Use",
  "사용자가 취소했습니다.": "Cancelled by the player.",
  "다이아 잔액이 부족합니다.": "Not enough diamonds.",
  "이미 완료한 영구 구매입니다.": "This permanent purchase is already complete.",
  "manifest에 선언된 액션과 일치하지 않는 요청입니다.": "This request does not match a manifest action.",
  "idempotencyKey가 필요합니다.": "An idempotency key is required.",
  "같은 idempotencyKey가 다른 구매 요청에 사용되었습니다.": "That idempotency key was already used for a different purchase.",
  "확인": "Confirm",
  "취소": "Cancel",
  "닫기": "Close",
  "뒤로": "Back",
  "계속": "Continue",
  "완료": "Complete",
  "저장 연결이 지연되었습니다. 항해는 계속하며 자동으로 다시 저장합니다.": "The save connection is delayed. Your voyage will continue and retry automatically.",
  "로컬 항해 모드 · 다이아 지갑 모의 연결": "Local voyage · simulated Diamond Wallet",
  "Language Miner 지갑 연결됨": "Language Miner Wallet connected",
  "구조 선원을 불러오는 중": "Calling the rescue crew",
  "귀향의 별을 밝히는 중": "Lighting the star of homecoming",
  "별과 파도 사이, 집으로 향하는 위대한 항해": "Between stars and waves, an epic voyage home",
  "아포나의 신탁탑": "A-paw-na's Oracle Tower",
  "포세이돈의 폭풍 항로": "Paw-seidon's Storm Route",
  "승리한 전투의 보상 정산이 기다리고 있습니다": "Battle rewards are waiting to be claimed.",
  "저장된 전투가 있습니다 · 안전한 턴 경계부터 계속": "A saved battle is ready · resume from a safe turn boundary",
  "항해 계속": "Continue Voyage",
  "첫 항해 시작": "Begin First Voyage",
  "저장된 항로와 전투 기록을 불러옵니다": "Load your saved route and battle record",
  "두 가지 조작만 익히고 실제 항로로 출항합니다": "Learn two controls, then set sail on a real route",
  "고양이를 당겨 튕기고 · 벽을 읽고 · 약점을 노려라": "Pull, ricochet, read the walls, and strike the weak point",
  "Meowthology · 지원 언어: 한국어 / English · 원본 음악·효과음 유지": "Meowthology · Languages: Korean / English · Original music and sound effects preserved",
  "영상 정보를 찾지 못했습니다. 이야기 화면으로 계속합니다.": "Video information was not found. Continuing to the story screen.",
  "항해의 기억": "Voyage Memory",
  "항해 회상": "Voyage Replay",
  "전체 에피소드를 불러오는 중…": "Loading the full episode…",
  "전체 에피소드 재생 · 언제든 SKIP으로 이야기 흐름을 계속할 수 있습니다": "Full episode playback · select SKIP at any time to continue the story",
  "이 에피소드 영상은 아직 준비 중입니다.": "This episode video is still being prepared.",
  "영상을 불러오지 못했습니다. 이야기 화면으로 계속합니다.": "Could not load the video. Continuing to the story screen.",
  "이 기기에서 지원하지 않는 영상 형식입니다.": "This video format is not supported on this device.",
  "영상 로딩 시간이 초과되었습니다. 이야기 화면으로 계속합니다.": "Video loading timed out. Continuing to the story screen.",
  "브라우저 정책으로 무음 재생 중 · 화면을 누르면 소리가 켜집니다": "Muted by browser policy · select the screen to enable sound",
  "자동 재생을 시작하지 못했습니다. 이야기 화면으로 계속합니다.": "Autoplay could not start. Continuing to the story screen.",
  "별빛 항로를 펼치는 중": "Charting the starlit route",
  "동료의 기억을 불러오는 중": "Recalling a companion's memory",
  "편성 화면에서 새로운 동료의 능력과 우정 스킬을 확인할 수 있습니다.": "Review your new companion's abilities and Friendship Skill on the party screen.",
  "이 항로의 기믹은 스테이지 선택 화면과 전투 목표에서 다시 확인할 수 있습니다.": "Review this route's mechanics on the stage-select screen and in battle objectives.",
  "동료 맞이하기": "Welcome Companion",
  "항로 펼치기": "Open Route",
  "회상 닫기": "Close Replay",
  "연출 건너뛰기": "Skip Scene",
  "개발 항해에서는 실제 다이아를 사용하지 않습니다. 테스트 재화는 개발 항해실에서 보급하세요.": "Developer voyages never spend real diamonds. Grant test resources from the developer cabin.",
  "아직 실제 보상을 사용할 수 없는 상품입니다. 결제하지 않았습니다.": "This product has no usable reward yet. No purchase was made.",
  "purchaseId가 다른 구매에 이미 사용되었습니다.": "This purchase ID was already used for another purchase.",
  "사용하지 않은 전투 구조가 있습니다. 먼저 기존 전투를 이어가세요.": "An unused battle rescue is waiting. Resume that battle first.",
  "보물고 확장은 이미 적용되었습니다.": "The vault expansion is already applied.",
  "purchaseId가 다른 pending 구매에 사용되었습니다.": "This purchase ID is already attached to another pending purchase.",
  "pending 구매를 찾지 못했습니다.": "The pending purchase could not be found.",
  "사용하지 않은 전투 구조가 있어 추가 결제를 취소했습니다.": "Another battle rescue is unused, so the additional purchase was cancelled.",
  "이미 차감된 구조 기록이 다른 구조와 충돌합니다. 어느 쪽도 덮어쓰지 않았습니다.": "The charged rescue record conflicts with another rescue. Neither record was overwritten.",
  "차감 결과를 저장하지 못했습니다. 같은 구매 키로 복구할 수 있습니다.": "The spend result could not be saved. It can be recovered with the same purchase key.",
  "차감 거래 번호가 없어 보상을 복구할 수 없습니다.": "The reward cannot be recovered because the spend transaction ID is missing.",
  "보상 커밋용 pending 구매를 찾지 못했습니다.": "The pending purchase needed to commit the reward was not found.",
  "전투 구조 구매 정보가 완전하지 않습니다.": "Battle rescue purchase information is incomplete.",
  "사용하지 않은 전투 구조가 있어 새 구조로 덮어쓸 수 없습니다.": "An unused battle rescue exists and cannot be overwritten.",
  "가호 재선택 구매 정보가 올바르지 않습니다.": "Blessing reroll purchase information is invalid.",
  "선원": "Crew",
  "유물": "Relics",
  "항해": "Voyage",
  "칭호": "Titles",
  "소리 · 언어": "Audio & Language",
  "화면 · 접근성": "Display & Accessibility",
  "고양이 오디세이 신탁 소환 1회": "Cat Odyssey · Oracle Summon ×1",
  "고양이 오디세이 신탁 소환 10회": "Cat Odyssey · Oracle Summon ×10",
  "고양이 오디세이 구조 요청": "Cat Odyssey · Battle Rescue",
  "고양이 오디세이 가호 재선택": "Cat Odyssey · Blessing Reroll",
  "고양이 오디세이 폭풍 항로 추가 출항": "Cat Odyssey · Extra Storm Route Run",
  "고양이 오디세이 토벌 열쇠 보충": "Cat Odyssey · Raid Key Refill",
  "고양이 오디세이 각성 재료 보충": "Cat Odyssey · Awakening Materials",
  "고양이 오디세이 보물고 확장": "Cat Odyssey · Vault Expansion",
  "구조 기록이 현재 콘텐츠와 맞지 않아 소비하지 않았습니다.": "The rescue record does not match the current content and was not consumed.",
  "구조 전투를 복원하지 못해 기록을 소비하지 않았습니다.": "The rescue battle could not be restored, so its record was not consumed.",
  "항구로 귀환": "Return to Harbor",
  "현재 전투 진행은 사라집니다. 귀환할까요?": "Current battle progress will be lost. Return to the harbor?",
  "진행 중인 전투 포기": "Abandon Active Battle",
  "진행 중 전투": "active battle",
});

export const CORE_ENGLISH_RULES: readonly TranslationRule[] = Object.freeze([
  {
    pattern: /^항해 준비에 실패했습니다:\s*(.+)$/u,
    replacement: (_match, detail) => `Failed to prepare the voyage: ${detail}`,
  },
  {
    pattern: /^\+ 버튼으로 (\d+)% 복원$/u,
    replacement: (_match, amount) => `Press + to restore ${amount}%`,
  },
  {
    pattern: /^(.+)을 저장하지 못했습니다\.$/u,
    replacement: (_match, label) => `Could not save ${label}.`,
  },
  {
    pattern: /^이전 결제 (\d+)건의 보상을 안전하게 복구했습니다\.$/u,
    replacement: (_match, count) => `Safely restored rewards from ${count} previous purchase${count === "1" ? "" : "s"}.`,
  },
  {
    pattern: /^확인 중인 결제 (\d+)건이 있습니다\. 같은 구매를 다시 누르면 이어서 확인합니다\.$/u,
    replacement: (_match, count) => `${count} purchase${count === "1" ? " is" : "s are"} still being verified. Select the same purchase to continue.`,
  },
  {
    pattern: /^필요 다이아:\s*([\d,]+)$/u,
    replacement: (_match, amount) => `Diamonds required: ${amount}`,
  },
  {
    pattern: /^현재 잔액:\s*([\d,]+)$/u,
    replacement: (_match, amount) => `Current balance: ${amount}`,
  },
  {
    pattern: /^스킬라 토벌 (\d+)페이즈$/u,
    replacement: (_match, phase) => `Scylla Raid · Phase ${phase}`,
  },
  {
    pattern: /^(.+) 승리 보상 정산이 기다리고 있습니다$/u,
    replacement: (_match, mode) => `${mode} victory rewards are waiting to be claimed.`,
  },
  {
    pattern: /^결제한 구조 전투가 기다립니다 · (.+)$/u,
    replacement: (_match, stage) => `Your purchased rescue battle is waiting · ${stage}`,
  },
  {
    pattern: /^일부 항해 자료를 불러오지 못했습니다 · (.+)\n기본 그림으로 안전하게 계속합니다$/u,
    replacement: (_match, key) => `Some voyage assets could not be loaded · ${key}\nContinuing safely with fallback art`,
  },
  {
    pattern: /^구매 기록을 안전하게 저장할 수 없어 결제를 시작하지 않았습니다\. 저장이 복구되면 다시 시도하세요\. \((.+)\)$/u,
    replacement: (_match, detail) => `The purchase did not start because its record could not be saved safely. Try again after saving recovers. (${detail})`,
  },
  {
    pattern: /^(.+) 전투 기록이 남아 있습니다\. 이 기록과 미정산 전투표를 포기하고 새 전투를 시작할까요\?$/u,
    replacement: (_match, stage) => `${stage} has an active battle record. Abandon it and any unsettled battle ticket to begin a new battle?`,
  },
]);
