import type { EnglishCatalog, TranslationRule } from "../catalogTypes";
import { CAT_ODYSSEY_GLOSSARY } from "../glossary";
import { CONTENT_ENGLISH_CATALOG } from "./content.en";
import { CORE_ENGLISH_CATALOG } from "./core.en";

/** Short labels that are also embedded inside dynamic scene copy. */
const SCENE_TERM_CATALOG: EnglishCatalog = Object.freeze({
  "전체": "All",
  "반사": "Ricochet",
  "관통": "Pierce",
  "중량": "Heavy",
  "폭발": "Burst",
  "지원": "Support",
  "바다": "Sea",
  "태양": "Sun",
  "달": "Moon",
  "폭풍": "Storm",
  "대지": "Earth",
  "영혼": "Spirit",
  "전투력": "Power",
  "레벨": "Level",
  "등급": "Rarity",
  "이름": "Name",
  "진행": "Progress",
  "수집": "Collected",
  "골드": "Gold",
  "영웅 경험": "Hero XP",
  "재료": "Materials",
  "각성석": "Awakening Stones",
  "유물 가루": "Relic Dust",
  "운명 가루": "Fate Dust",
  "토벌 열쇠": "Raid Keys",
  "조각": "Shards",
  "영웅": "Hero",
  "유물": "Relic",
  "칭호": "Title",
  "해제": "Unequip",
  "장착": "Equip",
  "잠김": "Locked",
  "보유 중": "Owned",
  "미보유": "Not Owned",
  "현재 장착 중": "Equipped",
  "클리어": "Cleared",
  "미클리어": "Uncleared",
  "없음": "None",
  "미공개": "Hidden",
  "항로 보스": "Route Boss",
  "핵심 항로": "Main Route",
  "모험 항로": "Adventure Route",
  "신탁탑": "Oracle Tower",
  "폭풍 항로": "Storm Route",
  "스킬라 토벌": "Scylla Raid",
  "해류 전투": "Current Battle",
  "정예 습격": "Elite Assault",
  "주간 폭풍의 눈": "Weekly Eye of the Storm",
  "신의 축복": "Divine Blessing",
  "항로의 저주": "Route Curse",
  "표류 항구": "Drifting Harbor",
  "반사형": "Ricochet",
  "관통형": "Pierce",
  "중량형": "Heavy",
  "폭발형": "Burst",
  "지원형": "Support",
  "반사형 · 벽 연계": "Ricochet · Wall Combo",
  "관통형 · 직선 돌파": "Pierce · Line Breaker",
  "중량형 · 강한 충돌": "Heavy · High Impact",
  "폭발형 · 범위 피해": "Burst · Area Damage",
  "지원형 · 회복과 제어": "Support · Healing & Control",
  "귀향": "Homecoming",
  "괴수 사냥": "Monster Hunt",
  "대항해": "Grand Voyage",
  "신성": "Divine",
  "모든 적 격파": "Defeat All Enemies",
  "적 전멸": "Defeat All Enemies",
  "약점 부위 파괴": "Break Weak Points",
  "부위 파괴": "Break Parts",
  "조립": "Assemble",
  "뗏목 부품 조립": "Assemble Raft Parts",
  "생존": "Survive",
  "제한 턴 생존": "Survive the Turn Limit",
  "보호": "Protect",
  "대상 보호·구출": "Protect or Rescue the Target",
  "봉인": "Seal",
  "봉인 완성": "Complete the Seal",
  "탈출": "Escape",
  "탈출 지점 도달": "Reach the Escape Point",
  "여섯 운명을 읽은 자": "Reader of Six Fates",
  "아포나가 선택한 선장": "A-paw-na's Chosen Captain",
  "해협의 인연": "Bond of the Strait",
  "스킬라의 벗": "Friend of Scylla",
  "별을 좇는 항해자": "Star-Chasing Voyager",
  "파도를 읽는 선장": "Wave-Reading Captain",
  "운명을 되튕긴 자": "One Who Ricocheted Fate",
  "귀향의 별잡이": "Homecoming Starcatcher",
  "별바다의 정복자": "Conqueror of the Starry Sea",
});

const SCENE_FIXED_CATALOG: EnglishCatalog = Object.freeze({
  // Harbor and route selection.
  "이타카 전초항": "Itha-Cat Forward Harbor",
  "귀향선 · 아르고냥": "Homecoming Ship · Argo-nyan",
  "오늘의 항해": "Today's Voyage",
  "항로 선택": "Select Route",
  "엔드게임 승리 정산 계속": "Continue Endgame Victory Settlement",
  "승리 보상 정산 계속": "Continue Reward Settlement",
  "결제한 구조 전투 계속": "Resume Purchased Rescue Battle",
  "중단한 전투 계속": "Resume Interrupted Battle",
  "선내 시설": "Ship Facilities",
  "선원 편성": "Party",
  "영웅 · 성장": "Heroes · Growth",
  "별의 신탁": "Oracle of the Stars",
  "영웅 소환": "Hero Summon",
  "끝없는 해역": "Endless Waters",
  "탑 · 폭풍 · 토벌": "Tower · Storm · Raid",
  "항해 도감": "Voyage Codex",
  "개발 항해실": "Developer Cabin",
  "항해 회상 · 전체 에피소드": "Voyage Replay · Full Episodes",
  "시청한 전체본은 다시 볼 수 있습니다 · 미시청 에피소드는 항해 중 해금됩니다": "Replay watched episodes · unseen episodes unlock during the voyage",
  "▶ 전체본 재생": "▶ Play Full Episode",
  "스토리에서 해금": "Unlock in Story",
  "영상 준비 중": "Video in Production",
  "‹ 이전": "‹ Previous",
  "다음 ›": "Next ›",
  "대해도를 펼치는 중": "Opening the grand sea chart",
  "대해도": "Grand Sea Chart",
  "항로 이야기 다시 보기": "Replay Route Story",
  "항로 이야기 미해금": "Route Story Locked",
  "첫 출항 시 이야기가 열립니다": "The story unlocks on your first departure",
  "항로를 먼저 해금하세요": "Unlock this route first",
  "항로 봉인": "Route Sealed",
  "이전 항로의 수호자를 쓰러뜨리면 해도가 열린다": "Defeat the previous route's guardian to open the chart",
  "재도전": "Retry",
  "출항": "Set Sail",
  "잠긴 항로": "Locked Route",
  "첫 돌파 보상 · 수령 완료": "First-Clear Reward · Claimed",
  "첫 클리어로 1성을 획득하세요": "Clear the stage to earn 1 star",
  "3성 달성 · 기록 단축과 연쇄 갱신에 도전하세요": "3 stars earned · improve your time and combo record",
  "항로 이야기를 먼저 확인하세요.": "View the route story first.",
  "앞 스테이지를 먼저 클리어하세요.": "Clear the previous stage first.",
  "전투 불능 없이 생존": "Survive without any hero falling",
  "전투 불능 없이 · 남은 HP 65% 이상": "No heroes fallen · finish with at least 65% HP",
  "전투 불능 없이 보호 완료": "Complete the protection objective with no heroes fallen",
  "전투 불능 없이 · 남은 HP 75% 이상": "No heroes fallen · finish with at least 75% HP",
  "최고 연쇄 3 HIT 이상으로 봉인": "Complete the seal with a best combo of at least 3 HIT",
  "최고 연쇄 5 HIT · 남은 HP 60% 이상": "Best combo 5 HIT · finish with at least 60% HP",
  "1성 · 스테이지 클리어": "1 Star · Clear the Stage",
  "스테이지 클리어": "Clear the Stage",

  // Route mechanics and collection copy.
  "이동 범퍼 · 파도 해류": "Moving Bumpers · Wave Currents",
  "감속장 · 동료 구출": "Slow Field · Companion Rescue",
  "감속장 · 선원 구조": "Slow Field · Crew Rescue",
  "파괴 바위 · 후방 약점": "Breakable Rocks · Rear Weak Point",
  "파괴 암석 · 후방 약점": "Breakable Rocks · Rear Weak Point",
  "바람 벡터 · 이동 관문": "Wind Vectors · Moving Gates",
  "일방 반사벽 · 변신": "One-Way Mirror Wall · Transformation",
  "일방 거울벽 · 변신": "One-Way Mirror Wall · Transformation",
  "쌍방 차원문 · 영체 벽": "Paired Portals · Spirit Walls",
  "쌍둥이 차원문 · 영혼벽": "Paired Portals · Spirit Walls",
  "회전 음파 · 범퍼": "Rotating Sound Wave · Bumpers",
  "소용돌이 · 다중 부위 파괴": "Whirlpool · Multi-Part Break",
  "소용돌이 흡인 · 다중 부위 파괴": "Whirlpool Pull · Multi-Part Break",
  "접촉 금지 대상 · 피뢰침": "Forbidden Target · Lightning Rod",
  "금지 표적 · 피뢰침": "Forbidden Target · Lightning Rod",
  "방향 방패 · 열두 도끼": "Directional Shields · Twelve Axes",
  "방향 방패 · 열두 도끼선": "Directional Shields · Twelve-Axe Line",
  "항해 도감을 정리하는 중": "Organizing the Voyage Codex",
  "방향키·Tab 항목 이동  ·  Enter 선택  ·  Esc 항구": "Arrow keys/Tab move · Enter select · Esc return to harbor",
  "아직 만나지 못한 고양이입니다.": "You have not met this cat yet.",
  "스토리 항해나 별의 신탁에서 인연을 맺으면 정보가 공개됩니다.": "Details unlock after meeting them in the story or Oracle.",
  "획득 전에는 이름과 효과가 기록되지 않습니다.": "Its name and effect remain hidden until acquired.",
  "첫 클리어 · 신탁탑 · 토벌 보상에서 발견 가능": "Found in first clears, the Oracle Tower, and raid rewards",
  "● 장착 중": "● Equipped",
  "보관 중": "In Storage",
  "효과 정보 없음": "No Effect Information",
  "이전 항로를 돌파하면 해역 이름과 기믹이 공개됩니다.": "Clear the previous route to reveal this area's name and mechanics.",
  "보스 해역": "Boss Stage",
  "대항해 진행": "Grand Voyage Progress",
  "귀향 서사 완주": "Homecoming Story Complete",
  "귀향 항해 진행 중": "Homecoming Voyage in Progress",
  "전투 기록": "Battle Record",
  "아직 기록 없음": "No Records Yet",
  "잠긴 칭호": "Locked Title",
  "조건을 달성하면 칭호의 이름과 이야기가 공개됩니다.": "Meet the requirement to reveal this title and its story.",
  "칭호를 해제했습니다": "Title unequipped",
  "칭호 설정을 저장하지 못했습니다": "Could not save the title setting",
  "영웅 도감": "Crew Codex",
  "유물 도감": "Relic Codex",
  "항해 기록": "Voyage Record",
  "칭호 목록": "Title List",
  "기록은 기존 캠페인·전투·엔드게임 저장값에서 안전하게 집계됩니다.": "Records are safely calculated from existing campaign, battle, and endgame saves.",
  "스킬라 토벌 대기 중": "Scylla Raid Ready",
  "특별한 항해 업적으로 얻은 칭호": "A title earned through an exceptional voyage feat",
  "특별 항해 보상": "Special Voyage Reward",
  "아직 항해 기록 없음": "No Voyage Record Yet",
  "미확인 해역": "Uncharted Stage",

  // Party, growth, and loadout tools.
  "선원 명부를 펼치는 중": "Opening the crew roster",
  "항해의 기억": "Voyage Memory",
  "전체 에피소드 파일을 확인하고 있습니다.\n영상이 없거나 읽을 수 없으면 편성 화면으로 바로 계속합니다.": "Checking the full episode file.\nIf it is missing or unreadable, the party screen will open immediately.",
  "영상 건너뛰고 편성": "Skip Video and Form Party",
  "아르고냥의 선원": "Argo-nyan's Crew",
  "3인 필수": "3 Heroes Required",
  "1~3인 출전": "Deploy 1–3 Heroes",
  "추가 전투 규칙 없음": "No Additional Battle Rules",
  "선원과 유물을 조합해 다음 항해를 준비하세요": "Combine crew and relics to prepare for the next voyage",
  "편성 도구": "Party Tools",
  "선원 명부": "Crew Roster",
  "자동·프리셋": "Auto & Presets",
  "전투 개시": "Start Battle",
  "편성 저장": "Save Party",
  "고위험 편성 · 출전은 가능합니다": "High-risk party · deployment is allowed",
  "폭풍 항로는 세 명이 필요합니다": "The Storm Route requires three heroes",
  "최소 한 명을 편성하세요": "Select at least one hero",
  "조건에 맞는 보유 선원이 없습니다\n필터를 한 번 더 눌러 바꿔 보세요": "No owned crew match these filters.\nSelect a filter again to change it.",
  "전술 추천": "Tactical Recommendation",
  "추천 인원": "Recommended Party Size",
  "스테이지 선택 필요": "Select a Stage",
  "목표·위험·적 구성을 분석해 보유 선원만 추천합니다.": "Recommendations analyze the objective, hazards, and enemies using owned crew only.",
  "잠긴 영웅과 금지 역할은 자동으로 제외합니다.": "Locked heroes and forbidden roles are excluded automatically.",
  "항로에서 스테이지를 선택하면 전술 추천을 사용할 수 있습니다.": "Select a stage from a route to use tactical recommendations.",
  "편성 프리셋 · 1~3인 저장": "Party Presets · Save 1–3 Heroes",
  "사용 불가 영웅 자동 정리": "Unavailable Heroes Removed",
  "빈 프리셋": "Empty Preset",
  "불러오기": "Load",
  "저장/덮기": "Save/Overwrite",
  "삭제": "Delete",
  "스킬라 3분대 편성": "Scylla Three-Squad Formation",
  "중복 없는 12명을 선택": "Select 12 Unique Heroes",
  "토벌 중에는 분대를 바꿀 수 없습니다. 앞 페이즈의 파괴 상태가 이어집니다.": "Squads cannot change during the raid. Destroyed parts carry into the next phase.",
  "각 분대 4명 · 영웅 중복 불가 · 세 전투를 모두 이겨야 최종 보상": "Four heroes per squad · no duplicates · win all three battles for the final reward",
  "보유 영웅 · 클릭하면 빈 분대에 순서대로 배치": "Owned Heroes · select to fill the next open squad slot",
  "토벌 출항": "Begin Raid",
  "3개 분대 검증 완료": "All Three Squads Validated",
  "12명을 편성하세요": "Assign 12 Heroes",
  "빈 자리": "Empty Slot",
  "항로 이탈": "Unavailable on Route",
  "층 규칙 금지": "Forbidden by Floor Rule",
  "잠긴 동료": "Locked Companion",
  "이번 도전 잠금": "Locked for This Run",
  "스토리": "Story",
  "신탁": "Oracle",
  "이 영웅은 현재 연속 도전에서 잠겨 있습니다": "This hero is locked for the current consecutive run",
  "현재 층은 이 클래스의 출전을 금지합니다": "This floor forbids this class",
  "메인 항해를 진행하면 승선하는 동료입니다": "This companion joins through the main voyage",
  "별의 신탁에서 만날 수 있는 동료입니다": "This companion can be found in the Oracle of the Stars",
  "편성 해제": "Remove",
  "마지막 슬롯 교체": "Replace Last Slot",
  "편성": "Add to Party",
  "성장 · 유물": "Growth & Relics",
  "영웅 훈련": "Hero Training",
  "1레벨 훈련": "Train 1 Level",
  "한계 돌파": "Ascension",
  "각성": "Awaken",
  "장착된 유물이 없습니다": "No relics equipped",
  "스테이지 첫 클리어로 유물을 획득하세요": "Earn relics from first-time stage clears",
  "유물 정련": "Refine Relic",
  "유물을 선택하면 실제 적용 효과를 확인할 수 있습니다": "Select a relic to review its applied effect",
  "유물을 선택하세요": "Select a relic",
  "정련": "Refine",
  "재료 보관함": "Material Storage",
  "재료 5개 정제": "Refine 5 Materials",
  "정제 재료 부족": "Not Enough Materials",
  "같은 재료 5개 필요": "Requires 5 of the same material",
  "각성석 보급": "Awakening Stone Supply",
  "10개 · 다이아 120": "10 · 120 Diamonds",
  "재료 보관함 · 정련 잠금": "Material Storage · Refinement Locks",
  "잠근 재료는 유물 자동 정련에서 차감되지 않습니다. 직접 5개 정제는 가능합니다.": "Locked materials are not consumed by automatic relic refinement. Manual batches of five are still allowed.",
  "정련 차감 보호 중": "Protected from Refinement",
  "정련 차감 가능": "Available for Refinement",
  "보유한 항해 재료가 없습니다": "No voyage materials owned",
  "보관함 닫기": "Close Storage",
  "정련 차감에서 보호했습니다": "Protected from refinement consumption",
  "정련 차감 보호를 해제했습니다": "Refinement protection removed",
  "재료 잠금을 저장하지 못했습니다": "Could not save material locks",
  "훈련을 완료했습니다": "Training complete",
  "각성 단계가 상승했습니다": "Ascension increased",
  "유물을 해제했습니다": "Relic unequipped",
  "유물을 장착했습니다": "Relic equipped",
  "유물을 정련했습니다": "Relic refined",
  "각성석 10개를 받았습니다": "Received 10 Awakening Stones",
  "성장 결과 저장이 지연되었습니다": "Growth Result Save Delayed",
  "재료와 성장 결과는 현재 게임에 이미 반영되어 있습니다.\n중복 차감을 막기 위해 저장이 끝날 때까지 다른 성장은 잠깁니다.": "Materials and growth results are already applied in this session.\nOther growth actions are locked until saving finishes to prevent duplicate costs.",
  "알 수 없는 저장 오류": "Unknown save error",
  "저장을 다시 완료하지 못했습니다": "Could not complete the save retry",
  "저장 다시 시도": "Retry Save",
  "현재 한계입니다. 먼저 각성하세요": "Current level cap reached. Awaken first",
  "최대 각성입니다": "Maximum ascension reached",
  "현재 레벨 상한에 도달해야 합니다": "Reach the current level cap first",
  "골드가 부족합니다": "Not enough Gold",
  "영웅 조각이 부족합니다": "Not enough Hero Shards",
  "각성석이 부족합니다": "Not enough Awakening Stones",
  "최대 정련입니다": "Maximum refinement reached",
  "유물 가루가 부족합니다": "Not enough Relic Dust",
  "항해 재료가 부족합니다": "Not enough voyage materials",
  "유물은 세 개까지만 장착할 수 있습니다": "You can equip up to three relics",
  "스테이지를 선택한 뒤 자동 추천을 사용할 수 있습니다": "Select a stage before using auto recommendation",
  "오래된 편성 프리셋 정리를 저장하지 못했습니다": "Could not save cleanup of an outdated party preset",
  "편성 프리셋을 저장하지 못했습니다": "Could not save the party preset",
  "불러올 수 있는 선원이 없습니다": "No available crew can be loaded",
  "편성 프리셋을 불러오지 못했습니다": "Could not load the party preset",
  "편성 프리셋을 삭제하지 못했습니다": "Could not delete the party preset",
  "결제한 구조 전투를 먼저 이어갑니다": "Resuming the purchased rescue battle first",
  "구조 기록 검증이 필요해 새 전투를 시작하지 않았습니다": "A new battle was not started because the rescue record needs verification",
  "진행 중 전투": "Active Battle",
  "진행 중인 전투 포기": "Abandon Active Battle",
  "기존 전투를 그대로 보존했습니다": "The existing battle was preserved",
  "기존 전투를 포기하지 못했습니다": "Could not abandon the existing battle",
  "폭풍 항로에는 쓰러지지 않은 영웅 세 명이 필요합니다": "The Storm Route requires three heroes who have not fallen",
  "현재 도전 규칙에 맞는 영웅을 1~3명 편성하세요": "Assign 1–3 heroes allowed by the current challenge rules",
  "전투 정산표를 준비하지 못했습니다": "Could not prepare the battle settlement",
  "저장 실패": "Save failed",
  "보물고가 가득 찼습니다": "The Vault Is Full",
  "이번 전투의 신규 유물은 첫 클리어 정산과 동시에\n등급에 맞는 유물 가루로 전환됩니다.\n출항 전에 보물고를 확장하거나, 전환을 확인하세요.": "The new relic from this battle will be converted into tier-appropriate Relic Dust during first-clear settlement.\nExpand the vault before departure, or confirm the conversion.",
  "유물 가루 전환 확인 · 출항": "Confirm Relic Dust Conversion · Set Sail",
  "보물고 확장 확인": "Review Vault Expansion",
  "끝없는 해역의 보물고 +20 상품으로 이동": "Go to the +20 Vault expansion in Endless Waters",
  "출항 취소": "Cancel Departure",

  // Reward settlement.
  "항해 승리": "Voyage Victory",
  "전투 정산을 시작하지 못했습니다": "Could not start battle settlement",
  "이미 정산이 끝난 전투입니다. 보상은 중복 지급되지 않습니다.": "This battle has already been settled. Rewards will not be granted twice.",
  "복구할 수 있는 승리 정산표가 없습니다. 항구에서 다시 확인해 주세요.": "No recoverable victory settlement was found. Check again from the harbor.",
  "보상 저장을 완료하지 못했습니다": "Reward Save Incomplete",
  "보상은 현재 게임에 보존되어 있습니다.\n저장을 다시 시도해 안전하게 확정하세요.": "Rewards are preserved in the current session.\nRetry saving to confirm them safely.",
  "파괴한 부위와 열린 안전 지형이 다음 전투로 이어집니다.\n보상은 3페이즈 최종 승리 때 한 번만 정산됩니다.": "Destroyed parts and opened safe terrain carry into the next battle.\nRewards are settled once after the final Phase 3 victory.",
  "끝없는 해역으로": "Return to Endless Waters",
  "정산 안내": "Settlement Notice",
  "항로로 돌아가기": "Return to Route",
  "항구로 귀환": "Return to Harbor",
  "획득 전리품": "Loot Acquired",
  "보물고 만석": "Vault Full",
  "중복 유물": "Duplicate Relic",
  "새 항로가 해도에 나타났습니다": "A new route has appeared on the chart",
  "다음 해역": "Next Stage",
  "항로 정산": "Route Summary",
  "첫 돌파 · 영웅": "First Clear · Hero",
  "첫 돌파 · 유물": "First Clear · Relic",
  "첫 돌파 · 조각": "First Clear · Shards",
  "첫 돌파 · 재료": "First Clear · Material",
  "보물고 만석 전환": "Vault-Full Conversion",
  "중복 전환": "Duplicate Conversion",
  "이미 보유한 보상": "Reward Already Owned",
  "동료 승선": "Companion Joined",
  "무료 토벌 열쇠": "Free Raid Keys",

  // Summoning.
  "별의 신탁을 준비하는 중": "Preparing the Oracle of the Stars",
  "확인 중인 소환이 있습니다. 소환 버튼을 누르면 같은 결과로 이어서 확인합니다.": "A summon is still being verified. Select the summon button to continue with the same result.",
  "귀향을 비추는 태양": "The Sun That Lights the Way Home",
  "상시 신탁": "Permanent Oracle",
  "기간 신탁": "Limited Oracle",
  "신탁 1회": "Summon ×1",
  "신탁 10회": "Summon ×10",
  "다이아 100": "100 Diamonds",
  "다이아 900 · 1회 보너스": "900 Diamonds · 1 Bonus Pull",
  "10회 신탁은 ★4 이상 영웅을 최소 1명 보장합니다": "A 10-pull guarantees at least one ★4 or higher hero",
  "스토리 동료는 합류 전 조각만 획득 · 중복 영웅은 각성 조각으로 변환": "Story companions grant shards until they join · duplicates convert into Awakening Shards",
  "확률 · 전체 목록": "Rates & Full Pool",
  "최근 소환 기록": "Recent Summons",
  "픽업 확정 활성": "Featured Guarantee Active",
  "운명 재봉합": "Reweave Fate",
  "다음 ★5는 픽업 확정": "Next ★5 is guaranteed featured",
  "승선 명부 보기": "View Crew Roster",
  "이전 소환 보상을 복구했습니다. 소환 기록에서 결과를 확인하세요.": "Previous summon rewards were recovered. Review the result in summon history.",
  "소환 확인에 실패했습니다.": "Summon verification failed.",
  "황금빛 운명이 응답했습니다": "Golden Fate Has Answered",
  "신탁 결과 확인": "Confirm Summon Results",
  "신탁 확률 및 전체 목록": "Oracle Rates & Full Pool",
  "픽업 실패 후 다음 ★5는 픽업 확정 · 10회 소환은 ★4 이상 1회 보장": "After missing the featured hero, the next ★5 is guaranteed featured · a 10-pull guarantees one ★4 or higher",
  "중복은 조각과 운명 가루로 변환": "Duplicates convert into shards and Fate Dust",
  "합류 전: 조각": "Before Joining: Shards",
  "종료일 없는 상시 배너": "Permanent Banner",
  "기간 배너": "Limited Banner",
  "아직 소환 기록이 없습니다": "No summon history yet",
  "조각 변환": "Shard Conversion",
  "이미 다음 ★5 픽업 확정이 활성화되어 있습니다.": "The next ★5 featured guarantee is already active.",
  "다음 ★5 영웅의 픽업 확정이 활성화되었습니다.": "The featured guarantee for the next ★5 hero is now active.",
  "운명 재봉합을 저장하지 못했습니다.": "Could not save Reweave Fate.",

  // Endgame.
  "주간 항로 저장 실패": "Failed to save weekly route",
  "메인 항해 너머의 시련": "Trials Beyond the Main Voyage",
  "스킬라 항해 인연": "Scylla Voyage Bond",
  "모든 마일스톤 달성": "All Milestones Reached",
  "전 티어 달성": "All Tiers Reached",
  "폭풍 출항": "Storm Departure",
  "보물고 확장 완료": "Vault Expansion Complete",
  "보물고 +20": "Vault +20",
  "다이아 50": "50 Diamonds",
  "다이아 180 · 1회": "180 Diamonds · One Time",
  "사냥 전리품으로 열쇠 제작": "Craft a Key from Hunt Trophies",
  "아직 봉인된 해역입니다": "This area is still sealed",
  "전투 정보를 찾지 못했습니다": "Battle information not found",
  "추가 고정 보상 없음": "No Additional Fixed Rewards",
  "진행 중인 토벌 · 열쇠 추가 소비 없음": "Raid in Progress · no additional key cost",
  "입장 시 토벌 열쇠 1개 소비": "Consumes 1 Raid Key on entry",
  "주간 무료 전투 소진 · 폭풍 추가 출항권 1개 소비": "Weekly free battles used · consumes 1 Extra Storm Entry",
  "기본 입장 무료": "Base entry is free",
  "적용 규칙": "Active Rules",
  "• 추가 규칙 없음": "• No Additional Rules",
  "실제 정산": "Actual Settlement",
  "편성으로 이동": "Go to Party",
  "상세 닫기": "Close Details",
  "이번 주 기본 폭풍 전투를 완료했습니다. 추가 출항권이 필요합니다.": "This week's base Storm battles are complete. An Extra Storm Entry is required.",
  "토벌 열쇠가 필요합니다. 아래에서 보급할 수 있습니다.": "A Raid Key is required. You can obtain one below.",
  "가호 재선택": "Reroll Blessings",
  "다이아 30": "30 Diamonds",
  "나중에 선택": "Choose Later",
  "항로 선택 저장이 지연되었습니다": "Route Choice Save Delayed",
  "선택 결과는 현재 항로에 이미 반영되어 있습니다. 중복 선택을 막기 위해 저장부터 완료합니다.": "The choice is already applied to the current route. Saving must finish first to prevent duplicate choices.",
  "짧아진 예측선": "Shortened Prediction Line",
  "솟구치는 해류": "Rising Current",
  "부서지기 쉬운 벽": "Fragile Walls",
  "응급 수리": "Emergency Repairs",
  "선체와 선원 응급 수리": "Emergency Hull and Crew Repairs",
  "선원 교대": "Crew Swap",
  "선원 한 명 교대": "Swap One Crew Member",
  "영웅 한 명 구조": "Rescue One Hero",
  "쓰러진 영웅 한 명 복귀": "Restore One Fallen Hero",
  "저주 하나 정화": "Cleanse One Curse",
  "항구 보급품": "Harbor Supplies",
  "항구 보급품 수령": "Collect Harbor Supplies",
  "항로 상태에 즉시 반영": "Applied to Route State Immediately",
  "열쇠 제작 저장이 지연되었습니다": "Key Craft Save Delayed",
  "재료 차감과 토벌 열쇠는 현재 게임에 이미 반영되어 있습니다. 중복 제작을 막기 위해 저장부터 완료합니다.": "The material cost and Raid Key are already applied in this session. Saving must finish first to prevent duplicate crafting.",
  "가호 선택 노드에서만 후보를 다시 고를 수 있습니다.": "Blessings can only be rerolled at a Blessing node.",
  "새로 제시할 가호 후보가 부족합니다.": "There are not enough new Blessing candidates.",
  "가호 재선택 구매 정보가 현재 항로와 일치하지 않습니다.": "The Blessing reroll purchase does not match the current route.",
  "새로운 가호 후보 세 개가 나타났습니다.": "Three new Blessing choices appeared.",
  "쓰러지지 않은 영웅 세 명을 편성하세요.": "Assign three heroes who have not fallen.",
  "폭풍 항로 선단을 편성했습니다.": "Storm Route party formed.",
  "자유 교대는 표류 항구의 선원 교대 서비스가 필요합니다.": "A free swap requires the crew-swap service at a Drifting Harbor.",
  "교대권을 사용했습니다.": "Swap charge used.",
  "항로 편성을 유지합니다.": "Current route party kept.",
  "현재 폭풍 노드에서 선택할 수 없는 항목입니다.": "This option is unavailable at the current Storm node.",
  "토벌 분대 편성이 저장되었습니다.": "Raid squad formation saved.",
  "토벌 열쇠가 필요합니다.": "A Raid Key is required.",
  "이번 주 기본 폭풍 전투를 모두 완료했습니다. 추가 출항권이 필요합니다.": "All base Storm battles for this week are complete. An Extra Storm Entry is required.",
  "올바른 토벌 분대를 편성하세요.": "Form a valid raid squad.",
  "4명 · 다른 분대와 중복 불가": "4 Heroes · No Duplicates Across Squads",
  "3명": "3 Heroes",
  "4명 전용 분대": "Four-Hero Squad Only",
  "영웅 중복 불가": "No Duplicate Heroes",
  "액티브 스킬 봉인": "Active Skills Sealed",
  "우정 스킬 봉인": "Friendship Skills Sealed",
  "약점 공략 강화": "Weak-Point Strategy Enhanced",

  // Debug cabin.
  "실제 저장과 다이아 지갑은 이 항해에 연결되지 않습니다.": "Your real save and Diamond Wallet are not connected to this voyage.",
  "선장의 비밀 해도": "Captain's Secret Chart",
  "휘발성 시험 항해": "Volatile Test Voyage",
  "시험 해도 각인": "Test Chart Imprints",
  "스토리 전부 개방": "Unlock All Story",
  "43 스테이지 · EP1–20 회상": "43 Stages · EP1–20 Replay",
  "엔드 콘텐츠 개방": "Unlock Endgame",
  "탑 · 폭풍 · 스킬라 입장": "Tower · Storm · Scylla Access",
  "전 선원 최대 성장": "Max All Crew",
  "16명 · 레벨 60 · 각성 5": "16 Heroes · Level 60 · Ascension 5",
  "시험 보급 채우기": "Fill Test Supplies",
  "골드 · 재료 · 전 유물": "Gold · Materials · All Relics",
  "전체 테스트 준비": "Prepare Full Test State",
  "모든 개방과 보급을 한 번에": "Unlock and supply everything at once",
  "진행 중 항해 정리": "Clear Active Runs",
  "전투 · 정산 · 엔드런 초기화": "Reset battles · settlements · endgame runs",
  "바로 출항": "Quick Departure",
  "항로": "Route",
  "시험 항해 시작 상태로 복원": "Restore Test Voyage Starting State",
  "이 탭을 열었을 때의 실제 저장 복제본으로만 되돌립니다.": "Restores only the real-save copy made when this tab opened.",
  "항구로 돌아가기": "Return to Harbor",
  "주소에서 ?catDebug=1을 제거하고 다시 열면 일반 저장으로 복귀합니다.": "Remove ?catDebug=1 from the address and reopen to return to the normal save.",
  "시험 항해 시작 상태를 복원했습니다. 실제 저장은 처음부터 변경되지 않았습니다.": "Test voyage starting state restored. The real save was never changed.",

  // Settings copy introduced with language persistence.
  "스토리, 영웅, 장비, 재료와 설정이 처음 상태로 돌아갑니다. 언어 선택과 학습으로 얻은 다이아 잔액은 유지됩니다.": "Story, heroes, equipment, materials, and settings return to their initial state. Your language choice and Diamonds earned through learning are kept.",

  // Collection/meta labels and descriptions visible outside battle.
  "햇살 드는 섬과 폭풍 해안": "Sunlit Island and Storm Coast",
  "꿈꾸는 로토스 정원": "Dreaming Lotus Garden",
  "외눈박이 동굴": "Cyclops Cave",
  "부유 바람 궁전과 거인 항구": "Floating Wind Palace and Giant Harbor",
  "마법의 아이아이아 정원": "Enchanted Aeaea Garden",
  "저승의 기억 강": "Underworld River of Memory",
  "달빛 사이렌 암초": "Moonlit Siren Reef",
  "검은 절벽 해협": "Black-Cliff Strait",
  "황금빛 태양 목장": "Golden Solar Pasture",
  "이타-캣 항구와 궁전": "Itha-Cat Harbor and Palace",
  "가까운 적 화살비": "Arrow Rain on the Nearest Enemy",
  "조준선 관통": "Pierce Along the Aim Line",
  "아군 투사체 방어": "Projectile Guard for All Allies",
  "아군 회복": "Heal Allies",
  "지속 회복": "Regeneration",
  "연쇄 반사": "Chain Ricochet",
  "밀쳐내기 파동": "Push Wave",
  "교차 베기": "Cross Slash",
  "임시 벽 생성": "Create a Temporary Wall",
  "약점 표식": "Mark Weak Point",
  "순풍 부여": "Grant Tailwind",
  "적 축소": "Shrink Enemy",
  "공격 예고 연장": "Extend Enemy Telegraph",
  "벽 통과": "Wall Phase",
  "태양륜": "Solar Ring",
  "추격타": "Follow-Up Shot",
  "속박": "Bind",
  "예상선 연장": "Extend Prediction Line",
  "약점 피해 증가": "Increase Weak-Point Damage",
  "동료 추가 발사": "Launch an Ally",
  "방패 파괴": "Shield Break",
  "기절": "Stun",
  "약점 노출": "Reveal Weak Point",
  "적 공격 지연": "Delay Enemy Attack",
  "약화 해제": "Cleanse Debuffs",
  "속도 증가": "Increase Speed",
  "임시 범퍼": "Temporary Bumper",
  "발사 속도 증가": "Increase Launch Speed",
  "피해 대신 받기": "Redirect Damage",
  "잔상 연타": "Afterimage Strikes",
  "궤적 분신": "Trajectory Clone",
  "전방위 공격": "Radial Attack",
  "동료 부활": "Revive Companion",
  "표식 광선": "Marked-Target Beam",
  "차원문 설치": "Create Portal Pair",
  "완전 예상 궤적": "Perfect Trajectory Preview",
  "약점 피해": "Weak-Point Damage",
  "대기 중 피해 감소": "Stationary Damage Reduction",
  "첫 공격 카운트 지연": "Delay First Attack Countdown",
  "첫 발사 속도": "First-Launch Speed",
  "관통 후 속도 유지": "Retained Speed after Piercing",
  "임시 벽 내구도": "Temporary Wall Durability",
  "연속 약점 보너스": "Consecutive Weak-Point Bonus",
  "첫 클리어 재료": "First-Clear Materials",
  "보스 피해": "Boss Damage",
  "후방 피해": "Rear-Hit Damage",
  "우정 접촉 범위": "Friendship Contact Radius",
  "파괴 부위 피해": "Breakable-Part Damage",
  "소용돌이 저항": "Whirlpool Resistance",
  "중량형 질량": "Heavy-Class Mass",
  "첫 기절 지속": "First-Stun Duration",
  "보스 부위 체력 표시": "Show Boss-Part HP",
  "바람·해류 저항": "Wind and Current Resistance",
  "파괴 벽 피해": "Breakable-Wall Damage",
  "아군 접촉 후 속도": "Speed after Ally Contact",
  "위험지대 이탈 회복": "Heal after Leaving a Hazard",
  "위험 벡터 표시": "Show Hazard Vectors",
  "저체력 반발력": "Low-HP Restitution",
  "항로 골드": "Route Gold",
  "전투당 최초 전투불능 부활": "First KO Revive per Battle",
  "약화 지속시간": "Debuff Duration",
  "액티브 충전 속도": "Active Charge Speed",
  "화상 피해": "Burn Damage",
  "3번째 접촉 연쇄번개": "Chain Lightning on Third Contact",
  "충돌 위상 통과": "Phase Through Collision",
  "첫 약점 치명타 확률": "First Weak-Point Critical Chance",
  "최저 체력 재생": "Lowest-HP Regeneration",
  "다음 적 행동 예고": "Preview Next Enemy Action",
  "예상 반사 횟수": "Predicted Ricochet Count",
  "현재 미연결": "Currently Unsupported",
  "첫 돌파 보상 수령 완료": "First-Clear Reward Claimed",
  "메인 캠페인 43개 스테이지를 완료해야 합니다.": "Complete all 43 main campaign stages.",
  "메인 캠페인을 완료해야 합니다.": "Complete the main campaign.",
  "스킬라·카리브디스 해협을 돌파해야 합니다.": "Clear the Scylla and Charybdis Strait.",
  "사용 가능한 전투 구조 기록이 없습니다.": "No usable battle rescue record exists.",
  "현재 전투와 구조 기록이 일치하지 않습니다.": "The current battle does not match the rescue record.",
  "구조 기록이 손상되어 자동으로 소비하지 않았습니다.": "The rescue record is damaged and was not consumed automatically.",
  "권장 전투력 정보 없음": "No Recommended Power Information",
  "현재 도전 규칙에 맞는 보유 영웅이 없습니다.": "No owned heroes satisfy the current challenge rules.",
  "잠금·금지 역할을 확인하세요.": "Review locked heroes and forbidden roles.",
  "방패 적": "Shielded Enemies",
  "원거리 공격": "Ranged Attacks",
  "지원·소환 적": "Support and Summoner Enemies",
  "역할과 속성을 분산해 대응 폭을 넓혔습니다.": "Roles and elements were diversified for broader coverage.",
  "신탁탑 30층 반복 보상": "Oracle Tower Floor 30 Repeat Reward",
  "퍼-씨 조각": "Purr-ce Shards",
  "전투 불능 없이 · 남은 HP 60% 이상": "No heroes fallen · finish with at least 60% HP",
  "선체 문양 · 스킬라의 물결": "Hull Pattern · Scylla's Wake",
  "선수상 · 여섯 머리": "Figurehead · Six Heads",
  "신화 선체 · 스킬라 항해": "Mythic Hull · Scylla Voyage",
  "칭호 · 해협의 인연": "Title · Bond of the Strait",
  "칭호 · 스킬라의 벗": "Title · Friend of Scylla",
  "여섯 갈래 운명을 읽어 낸 선장": "A captain who read the six branches of fate in the Oracle Tower",
  "마지막 신탁을 증명해 아포나의 인정을 받은 선장": "A captain recognized by A-paw-na after proving the final oracle",
  "스킬라 항해 인연 20을 달성한 해협의 동행자": "A companion of the strait who reached Scylla Voyage Bond 20",
  "스킬라 항해 인연 75를 달성한 오랜 벗": "A longtime friend who reached Scylla Voyage Bond 75",
  "수많은 해역에서 별 30개를 모아 항로를 밝힌 항해자": "A voyager who lit the routes by collecting 30 campaign stars",
  "캠페인 별 60개를 모아 바다의 변화를 읽어 낸 선장": "A captain who learned to read the sea after collecting 60 campaign stars",
  "캠페인 별 90개를 모아 불리한 운명마저 반사한 명사수": "A sharpshooter who ricocheted even an unfavorable fate after collecting 90 campaign stars",
  "캠페인 별 120개로 마지막 귀향길까지 밝혀 낸 항해사": "A navigator who lit the final road home with 120 campaign stars",
  "43개 해역의 별 129개를 모두 거머쥔 완전한 항해의 증표": "Proof of a perfect voyage that claimed all 129 stars across 43 stages",
  "신탁탑 29층 돌파": "Clear Oracle Tower Floor 29",
  "신탁탑 30층 돌파": "Clear Oracle Tower Floor 30",
  "스킬라 항해 인연 20 달성": "Reach Scylla Voyage Bond 20",
  "스킬라 항해 인연 75 달성": "Reach Scylla Voyage Bond 75",
  "캠페인 별 30개 달성": "Earn 30 Campaign Stars",
  "캠페인 별 60개 달성": "Earn 60 Campaign Stars",
  "캠페인 별 90개 달성": "Earn 90 Campaign Stars",
  "캠페인 별 120개 달성": "Earn 120 Campaign Stars",
  "모든 캠페인 스테이지 3성 달성 (129개)": "Earn 3 Stars on Every Campaign Stage (129 total)",
});

export const SCENE_ENGLISH_CATALOG: EnglishCatalog = Object.freeze({
  ...SCENE_TERM_CATALOG,
  ...SCENE_FIXED_CATALOG,
});

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function translateKnownTerm(value: string): string {
  const source = value.trim();
  return CAT_ODYSSEY_GLOSSARY[source]
    ?? CONTENT_ENGLISH_CATALOG[source]
    ?? CORE_ENGLISH_CATALOG[source]
    ?? SCENE_TERM_CATALOG[source]
    ?? SCENE_FIXED_CATALOG[source]
    ?? source;
}

function translateCompound(value: string): string {
  return value
    .split(/\s+·\s+/u)
    .map((part) => {
      const amount = /^(.*?)(\s+(?:[+×]|→)\s*[\d,.]+(?:%|회|턴|명|개|종|층|칸)?)$/u.exec(part);
      return amount
        ? `${translateKnownTerm(amount[1] ?? "")}${amount[2] ?? ""}`
        : translateKnownTerm(part);
    })
    .join(" · ");
}

function translateObjective(value: string): string {
  const counted = /^(.*?)(?:\s+(\d+)회)$/u.exec(value.trim());
  return counted
    ? `${translateKnownTerm(counted[1] ?? "")} ×${counted[2]}`
    : translateKnownTerm(value);
}

function translateCharacterList(value: string): string {
  return value.split(/\s+·\s+/u).map(translateKnownTerm).join(" · ");
}

const glossaryAlternation = Object.keys(CAT_ODYSSEY_GLOSSARY)
  .sort((left, right) => right.length - left.length)
  .map(escapeRegExp)
  .join("|");
const GLOSSARY_LIST_PATTERN = new RegExp(
  `^(?:${glossaryAlternation})(?:\\s+·\\s+(?:${glossaryAlternation}))*$`,
  "u",
);

export const SCENE_ENGLISH_RULES: readonly TranslationRule[] = Object.freeze([
  // Character names must always follow the canonical glossary, including lists.
  {
    pattern: GLOSSARY_LIST_PATTERN,
    replacement: (match) => translateCharacterList(match),
  },

  // Harbor and route status.
  { pattern: /^칭호 · (.+?)\s*›$/u, replacement: (_match, name) => `Title · ${translateKnownTerm(name ?? "")} ›` },
  { pattern: /^(\d+) \/ (\d+) 해역 돌파\s+·\s+(\d+)명 승선$/u, replacement: (_m, cleared, total, crew) => `${cleared} / ${total} stages cleared · ${crew} crew aboard` },
  { pattern: /^스킬라 (\d+)페이즈$/u, replacement: (_m, phase) => `Scylla · Phase ${phase}` },
  { pattern: /^(.+?) · (\d+)성 달성$/u, replacement: (_m, mode, stars) => `${translateKnownTerm(mode ?? "")} · ${stars}-star clear` },
  { pattern: /^(.+?) · 턴 (\d+)$/u, replacement: (_m, stage, turn) => `${translateKnownTerm(stage ?? "")} · Turn ${turn}` },
  { pattern: /^항해일지\s+(\d+)$/u, replacement: (_m, order) => `Voyage Log ${order}` },
  { pattern: /^보유 재화\s+·\s+각성석 ([\d,]+)\s+·\s+유물 가루 ([\d,]+)\s+·\s+항해 재료 ([\d,]+)$/u, replacement: (_m, stones, dust, materials) => `Resources · Awakening Stones ${stones} · Relic Dust ${dust} · Voyage Materials ${materials}` },
  { pattern: /^선원 (\d+)\/16 · 유물 (\d+)\/32$/u, replacement: (_m, crew, relics) => `Crew ${crew}/16 · Relics ${relics}/32` },
  { pattern: /^EP1–(\d+) 전체본$/u, replacement: (_m, episode) => `EP1–${episode} Full Episodes` },
  { pattern: /^항로 (\d+)\s+·\s+(핵심 항로|모험 항로)$/u, replacement: (_m, order, kind) => `Route ${order} · ${translateKnownTerm(kind ?? "")}` },
  { pattern: /^(.+?) (재도전|출항)$/u, replacement: (_m, stage, action) => `${translateKnownTerm(stage ?? "")} · ${action === "재도전" ? "Retry" : "Set Sail"}` },
  { pattern: /^(.+?)\s+·\s+권장 전투력 ([\d,]+)$/u, replacement: (_m, stage, power) => `${translateKnownTerm(stage ?? "")} · Recommended Power ${power}` },
  { pattern: /^목표 · (.+)$/u, replacement: (_m, objective) => `Objective · ${translateObjective(objective ?? "")}` },
  { pattern: /^최고 기록\s+(.+)$/u, replacement: (_m, record) => `Best Record · ${translateKnownTerm(record ?? "")}` },
  { pattern: /^반복 · 골드 ([\d,]+) · XP ([\d,]+)$/u, replacement: (_m, gold, xp) => `Repeat · Gold ${gold} · XP ${xp}` },
  { pattern: /^첫 돌파 · (.+)$/u, replacement: (_m, reward) => `First Clear · ${translateCompound(reward ?? "")}` },
  { pattern: /^먼저 항로 (\d+)의 마지막 스테이지를 클리어하세요\.$/u, replacement: (_m, route) => `Clear the final stage of Route ${route} first.` },
  { pattern: /^먼저 ‘(.+)’ 스테이지를 클리어하세요\.$/u, replacement: (_m, stage) => `Clear “${translateKnownTerm(stage ?? "")}” first.` },
  { pattern: /^(.+) 조건으로 ([23])성에 도전하세요$/u, replacement: (_m, condition, stars) => `Meet “${translateKnownTerm(condition ?? "")}” to challenge for ${stars} stars` },
  { pattern: /^(\d+)턴 이내 승리$/u, replacement: (_m, turns) => `Win within ${turns} turns` },
  { pattern: /^(\d+)턴 이내 · 최고 연쇄 4 HIT$/u, replacement: (_m, turns) => `Within ${turns} turns · best combo 4 HIT` },
  { pattern: /^(\d+)턴 이내 · 전원 생존 탈출$/u, replacement: (_m, turns) => `Escape within ${turns} turns with everyone alive` },
  { pattern: /^(\d+)턴 이내 · 전원 생존 · 남은 HP (\d+)% 이상$/u, replacement: (_m, turns, hp) => `Within ${turns} turns · everyone alive · at least ${hp}% HP remaining` },
  { pattern: /^(\d+)턴 이내 목표 파괴$/u, replacement: (_m, turns) => `Destroy the target within ${turns} turns` },
  { pattern: /^(\d+)턴 이내 · 남은 HP (\d+)% 이상$/u, replacement: (_m, turns, hp) => `Within ${turns} turns · at least ${hp}% HP remaining` },
  { pattern: /^(\d+)턴 이내 조립 완료$/u, replacement: (_m, turns) => `Complete assembly within ${turns} turns` },
  { pattern: /^([23])성 · (.+)$/u, replacement: (_m, stars, condition) => `${stars} Stars · ${translateKnownTerm(condition ?? "")}` },

  // Collection and records.
  { pattern: /^(영웅 도감|유물 도감|항해 기록|칭호 목록) · (진행|수집) (\d+)(?: · 항로 (\d+)개)?$/u, replacement: (_m, tab, progress, amount, routes) => `${translateKnownTerm(tab ?? "")} · ${translateKnownTerm(progress ?? "")} ${amount}${routes ? ` · ${routes} routes` : ""}` },
  { pattern: /^Lv\.(\d+) · 각성 (\d+)$/u, replacement: (_m, level, awakening) => `Lv.${level} · Ascension ${awakening}` },
  { pattern: /^우정\s+(.+)$/u, replacement: (_m, skill) => `Friendship · ${translateKnownTerm(skill ?? "")}` },
  { pattern: /^액티브\s+(.+) · 충전 (\d+)턴$/u, replacement: (_m, skill, turns) => `Active · ${translateKnownTerm(skill ?? "")} · Charge ${turns} turns` },
  { pattern: /^T(\d+) · (.+) 세트 · 도감 (\d+)\/32$/u, replacement: (_m, tier, setName, index) => `T${tier} · ${translateKnownTerm(setName ?? "")} Set · Codex ${index}/32` },
  { pattern: /^(\d+)개 해역 · 진행 (\d+)\/(\d+)$/u, replacement: (_m, stages, completed, total) => `${stages} stages · Progress ${completed}/${total}` },
  { pattern: /^항로 (\d+) · (.+)$/u, replacement: (_m, order, route) => `Route ${order} · ${translateKnownTerm(route ?? "")}` },
  { pattern: /^진행 (\d+)\/(\d+) \((\d+)%\) · 별 (\d+)\/(\d+)(?: · 보스 격파 (.+))?$/u, replacement: (_m, completed, total, percent, stars, maxStars, boss) => `Progress ${completed}/${total} (${percent}%) · Stars ${stars}/${maxStars}${boss ? ` · Boss Defeated: ${translateKnownTerm(boss)}` : ""}` },
  { pattern: /^(.+?) · 보스 해역$/u, replacement: (_m, objective) => `${translateObjective(objective ?? "")} · Boss Stage` },
  { pattern: /^해역 (\d+)\/(\d+)\s+·\s+별 (\d+)\/(\d+)\s+·\s+항로 (\d+)\/(\d+)$/u, replacement: (_m, stages, totalStages, stars, maxStars, routes, totalRoutes) => `Stages ${stages}/${totalStages} · Stars ${stars}/${maxStars} · Routes ${routes}/${totalRoutes}` },
  { pattern: /^최근 항해 (.+)$/u, replacement: (_m, date) => `Last Voyage ${date}` },
  { pattern: /^승리 ([\d,]+)\s+·\s+패배 ([\d,]+)\s+·\s+최고 연쇄 (\d+)$/u, replacement: (_m, wins, losses, chain) => `Wins ${wins} · Losses ${losses} · Best Combo ${chain}` },
  { pattern: /^누적 피해 ([\d,]+)$/u, replacement: (_m, damage) => `Total Damage ${damage}` },
  { pattern: /^격파 보스 (\d+)\/(\d+)\s+·\s+(.+)$/u, replacement: (_m, defeated, total, names) => `Bosses Defeated ${defeated}/${total} · ${translateCompound(names ?? "")}` },
  { pattern: /^신탁탑\s+(\d+)\/30층$/u, replacement: (_m, floor) => `Oracle Tower · Floor ${floor}/30` },
  { pattern: /^폭풍 항로\s+주간 완주 (\d+)\/6\s+·\s+최고 점수 ([\d,]+)$/u, replacement: (_m, runs, score) => `Storm Route · Weekly Clears ${runs}/6 · Best Score ${score}` },
  { pattern: /^스킬라 항해 인연\s+(\d+)\/(\d+)$/u, replacement: (_m, bond, max) => `Scylla Voyage Bond ${bond}/${max}` },
  { pattern: /^스킬라 토벌 진행 중 · (\d+)페이즈$/u, replacement: (_m, phase) => `Scylla Raid in Progress · Phase ${phase}` },
  { pattern: /^해금 조건 · (.+)$/u, replacement: (_m, condition) => `Unlock Requirement · ${translateKnownTerm(condition ?? "")}` },
  { pattern: /^(.+) 칭호를 장착했습니다$/u, replacement: (_m, title) => `${translateKnownTerm(title ?? "")} title equipped` },
  { pattern: /^미확인 선원 (\d+)$/u, replacement: (_m, index) => `Unknown Crew ${index}` },
  { pattern: /^미확인 유물 (\d+)$/u, replacement: (_m, index) => `Unknown Relic ${index}` },
  { pattern: /^미해금 항로 (\d+)$/u, replacement: (_m, order) => `Locked Route ${order}` },
  { pattern: /^(.+) · (\d+)턴$/u, replacement: (_m, effect, turns) => `${translateKnownTerm(effect ?? "")} · ${turns} turns` },

  // Party setup, growth, and presets.
  { pattern: /^전투력 ([\d,]+) \/ 권장\((\d+)인 환산\) ([\d,-]+)\s+·\s+(.+)$/u, replacement: (_m, current, partySize, recommended, details) => `Power ${current} / Recommended (${partySize}-hero scale) ${recommended} · ${translateCompound(details ?? "")}` },
  { pattern: /^파티 전투력 ([\d,]+)\s+·\s+전투에 나설 동료를 1~3명 선택하세요$/u, replacement: (_m, power) => `Party Power ${power} · select 1–3 companions for battle` },
  { pattern: /^반복 골드 ([\d,]+) · XP ([\d,]+) \| (.+)$/u, replacement: (_m, gold, xp, firstClear) => `Repeat Gold ${gold} · XP ${xp} | ${translateCompound(firstClear ?? "")}` },
  { pattern: /^출전 (\d+) \/ 3$/u, replacement: (_m, selected) => `Deployed ${selected} / 3` },
  { pattern: /^승선 명부\s+(\d+)명$/u, replacement: (_m, count) => `Crew Roster · ${count}` },
  { pattern: /^(\d+)명으로 출전합니다$/u, replacement: (_m, count) => `Deploying ${count} hero${count === "1" ? "" : "es"}` },
  { pattern: /^역할 · (.+)$/u, replacement: (_m, role) => `Role · ${translateKnownTerm(role ?? "")}` },
  { pattern: /^속성 · (.+)$/u, replacement: (_m, element) => `Element · ${translateKnownTerm(element ?? "")}` },
  { pattern: /^레벨 · (.+)$/u, replacement: (_m, level) => `Level · ${level}` },
  { pattern: /^정렬 · (.+)$/u, replacement: (_m, sort) => `Sort · ${translateKnownTerm(sort ?? "")}` },
  { pattern: /^검색 결과 (\d+)명$/u, replacement: (_m, count) => `${count} Result${count === "1" ? "" : "s"}` },
  { pattern: /^함대 유물 (\d+) \/ 3$/u, replacement: (_m, count) => `Fleet Relics ${count} / 3` },
  { pattern: /^전술 추천 · (.+)$/u, replacement: (_m, objective) => `Tactical Recommendation · ${translateKnownTerm(objective ?? "")}` },
  { pattern: /^(\d+)인 자동 추천$/u, replacement: (_m, count) => `Auto-Recommend ${count}` },
  { pattern: /^(\d+)분대(?:\s+◀ 출전)?$/u, replacement: (match, squad) => `Squad ${squad}${match.includes("◀") ? " ◀ Active" : ""}` },
  { pattern: /^(\d+)페이즈 출항 준비$/u, replacement: (_m, phase) => `Prepare Phase ${phase}` },
  { pattern: /^(.+)\s+·\s+(\d+)턴$/u, replacement: (_m, name, turns) => `${translateKnownTerm(name ?? "")} · ${turns} turns` },
  { pattern: /^(\d+)페이즈 전투 개시$/u, replacement: (_m, phase) => `Start Phase ${phase}` },
  { pattern: /^Lv\.(\d+) · (.+)$/u, replacement: (_m, level, role) => `Lv.${level} · ${translateKnownTerm(role ?? "")}` },
  { pattern: /^(.+)\s+·\s+(.+)\s+·\s+각성 (\d+)$/u, replacement: (_m, epithet, heroClass, awakening) => `${translateKnownTerm(epithet ?? "")} · ${translateKnownTerm(heroClass ?? "")} · Ascension ${awakening}` },
  { pattern: /^각성 필요 · XP ([\d,]+) 보관 중$/u, replacement: (_m, xp) => `Ascension required · ${xp} XP stored` },
  { pattern: /^우정\s+✦\s+(.+)$/u, replacement: (_m, skill) => `Friendship ✦ ${translateKnownTerm(skill ?? "")}` },
  { pattern: /^액티브\s+◆\s+(.+)\s+·\s+충전 (\d+)턴$/u, replacement: (_m, skill, turns) => `Active ◆ ${translateKnownTerm(skill ?? "")} · Charge ${turns} turns` },
  { pattern: /^(.+) 성장$/u, replacement: (_m, hero) => `${translateKnownTerm(hero ?? "")} Growth` },
  { pattern: /^Lv\.(\d+) \/ (\d+)\s+·\s+각성 (\d+)\s+·\s+조각 (\d+)$/u, replacement: (_m, level, cap, awakening, shards) => `Lv.${level} / ${cap} · Ascension ${awakening} · Shards ${shards}` },
  { pattern: /^골드 ([\d,]+)$/u, replacement: (_m, gold) => `Gold ${gold}` },
  { pattern: /^각성석 ([\d,]+)\s+·\s+유물 가루 ([\d,]+)$/u, replacement: (_m, stones, dust) => `Awakening Stones ${stones} · Relic Dust ${dust}` },
  { pattern: /^다음 레벨 비용\s+골드 ([\d,]+)$/u, replacement: (_m, gold) => `Next Level Cost · Gold ${gold}` },
  { pattern: /^골드 ([\d,]+) · 조각 ([\d,]+) · 각성석 ([\d,]+)$/u, replacement: (_m, gold, shards, stones) => `Gold ${gold} · Shards ${shards} · Awakening Stones ${stones}` },
  { pattern: /^(.+) 정련$/u, replacement: (_m, relic) => `Refine ${translateKnownTerm(relic ?? "")}` },
  { pattern: /^골드 ([\d,]+) · 가루 ([\d,]+)$/u, replacement: (_m, gold, dust) => `Gold ${gold} · Dust ${dust}` },
  { pattern: /^차감 예정\s+(.+)$/u, replacement: (_m, materials) => `Planned Cost · ${translateCompound(materials ?? "")}` },
  { pattern: /^잠금 (\d+)종$/u, replacement: (_m, count) => `${count} Locked Type${count === "1" ? "" : "s"}` },
  { pattern: /^(.+) → 유물 가루 25$/u, replacement: (_m, material) => `${translateKnownTerm(material ?? "")} → 25 Relic Dust` },
  { pattern: /^보유 ([\d,]+) · (정련 차감 보호 중|정련 차감 가능)$/u, replacement: (_m, amount, state) => `Owned ${amount} · ${translateKnownTerm(state ?? "")}` },
  { pattern: /^유물 가루 \+(\d+)$/u, replacement: (_m, amount) => `Relic Dust +${amount}` },
  { pattern: /^(.+) · 저장 지연 후 완료$/u, replacement: (_m, message) => `${translateKnownTerm(message ?? "")} · completed after save delay` },
  { pattern: /^(.+) · 저장 완료$/u, replacement: (_m, message) => `${translateKnownTerm(message ?? "")} · save complete` },
  { pattern: /^프리셋 (\d+)에 현재 편성을 저장했습니다$/u, replacement: (_m, slot) => `Current party saved to Preset ${slot}` },
  { pattern: /^프리셋 (\d+)을 불러왔습니다$/u, replacement: (_m, slot) => `Preset ${slot} loaded` },
  { pattern: /^프리셋 (\d+)을 비웠습니다$/u, replacement: (_m, slot) => `Preset ${slot} cleared` },
  { pattern: /^(.+) 전투 기록이 남아 있습니다\. 이 기록과 미정산 전투표를 포기하고 새 전투를 시작할까요\?$/u, replacement: (_m, stage) => `A battle record for ${translateKnownTerm(stage ?? "")} remains. Abandon it and its unsettled battle ticket to start a new battle?` },
  { pattern: /^(.+) · 같은 출항 상태로 다시 저장하세요$/u, replacement: (_m, error) => `${translateKnownTerm(error ?? "")} · retry saving the same departure state` },
  { pattern: /^아군끼리 접촉하면 발동 · (.+)$/u, replacement: (_m, effects) => `Triggers when allies touch · ${translateCompound(effects ?? "")}` },
  { pattern: /^잠금 제외 (\d+)\/(\d+)$/u, replacement: (_m, available, requested) => `${available}/${requested} available after locks` },
  { pattern: /^(.+)\s+\(잠금 제외 (\d+)\/(\d+)\)$/u, replacement: (_m, consumed, available, requested) => `${translateCompound(consumed ?? "")} (${available}/${requested} available after locks)` },
  { pattern: /^(.+) · 골드 ×([\d.]+) · XP ×([\d.]+)(.*)$/u, replacement: (_m, label, gold, xp, bonuses) => `${translateKnownTerm(label ?? "")} · Gold ×${gold} · XP ×${xp}${bonuses ? translateCompound(bonuses) : ""}` },

  // Reward settlement and milestone banners.
  { pattern: /^(\d+)페이즈 돌파$/u, replacement: (_m, phase) => `Phase ${phase} Cleared` },
  { pattern: /^다음 · (.+)$/u, replacement: (_m, next) => `Next · ${translateKnownTerm(next ?? "")}` },
  { pattern: /^(\d+)분대 출항$/u, replacement: (_m, squad) => `Deploy Squad ${squad}` },
  { pattern: /^●\s+골드\s+\+([\d,]+)$/u, replacement: (_m, gold) => `●  Gold   +${gold}` },
  { pattern: /^✦\s+영웅 경험\s+\+([\d,]+) × (\d+)명$/u, replacement: (_m, xp, heroes) => `✦  Hero XP   +${xp} × ${heroes}` },
  { pattern: /^◆\s+재료\s+(.+)$/u, replacement: (_m, materials) => `◆  Materials   ${translateCompound(materials ?? "")}` },
  { pattern: /^⚔\s+최고 연쇄\s+(\d+) HIT$/u, replacement: (_m, combo) => `⚔  Best Combo   ${combo} HIT` },
  { pattern: /^(보물고 만석|중복 유물) · (.+) → 유물 가루 \+(\d+)$/u, replacement: (_m, reason, relic, amount) => `${translateKnownTerm(reason ?? "")} · ${translateKnownTerm(relic ?? "")} → Relic Dust +${amount}` },
  { pattern: /^칭호 (.+)$/u, replacement: (_m, title) => `Title · ${translateKnownTerm(title ?? "")}` },
  { pattern: /^(.+) \+(\d+) \(보유\)$/u, replacement: (_m, reward, amount) => `${translateKnownTerm(reward ?? "")} +${amount} (Owned)` },
  { pattern: /^(.+) \+(\d+)$/u, replacement: (_m, reward, amount) => `${translateKnownTerm(reward ?? "")} +${amount}` },
  { pattern: /^보유 골드 ([\d,]+)$/u, replacement: (_m, gold) => `Gold Owned ${gold}` },
  { pattern: /^각성석 ([\d,]+) · 유물 가루 ([\d,]+) · 토벌 열쇠 ([\d,]+)$/u, replacement: (_m, stones, dust, keys) => `Awakening Stones ${stones} · Relic Dust ${dust} · Raid Keys ${keys}` },
  { pattern: /^보물고 (\d+)\/(\d+)$/u, replacement: (_m, used, capacity) => `Vault ${used}/${capacity}` },
  { pattern: /^첫 돌파 · (영웅|유물|조각|재료)$/u, replacement: (_m, kind) => `First Clear · ${translateKnownTerm(kind ?? "")}` },
  { pattern: /^(보물고 만석 전환|중복 전환) · 유물 가루 \+(\d+)$/u, replacement: (_m, reason, amount) => `${translateKnownTerm(reason ?? "")} · Relic Dust +${amount}` },
  { pattern: /^중복 전환 · (.+) 조각 \+(\d+)$/u, replacement: (_m, hero, amount) => `Duplicate Conversion · ${translateKnownTerm(hero ?? "")} Shards +${amount}` },
  { pattern: /^골드 \+([\d,]+)$/u, replacement: (_m, amount) => `Gold +${amount}` },
  { pattern: /^각성석 \+(\d+)$/u, replacement: (_m, amount) => `Awakening Stones +${amount}` },
  { pattern: /^운명 가루 \+(\d+)$/u, replacement: (_m, amount) => `Fate Dust +${amount}` },
  { pattern: /^토벌 열쇠 \+(\d+)$/u, replacement: (_m, amount) => `Raid Keys +${amount}` },
  { pattern: /^외 (\d+)종$/u, replacement: (_m, count) => `${count} more type${count === "1" ? "" : "s"}` },
  { pattern: /^별 항해 (\d+)★ 달성 · 마일스톤 (\d+)개 연속 해금$/u, replacement: (_m, stars, count) => `${stars}★ Voyage · ${count} milestones unlocked in sequence` },
  { pattern: /^별 항해 (\d+)★ 마일스톤 달성$/u, replacement: (_m, stars) => `${stars}★ Voyage Milestone Reached` },
  { pattern: /^칭호 ‘(.+)’(?: · (.+))?$/u, replacement: (_m, title, resources) => `Title “${translateKnownTerm(title ?? "")}”${resources ? ` · ${translateCompound(resources)}` : ""}` },

  // Summon UI and disclosures.
  { pattern: /^(상시 신탁|기간 신탁) · ★5 픽업$/u, replacement: (_m, kind) => `${translateKnownTerm(kind ?? "")} · ★5 Featured` },
  { pattern: /^누적 신탁\s+([\d,]+)$/u, replacement: (_m, pulls) => `Total Summons ${pulls}` },
  { pattern: /^★5 천장까지\s+(\d+)회$/u, replacement: (_m, pulls) => `${pulls} until ★5 pity` },
  { pattern: /^★5 3%$/u, replacement: () => "★5 3%" },
  { pattern: /^★4 20% · ★3 77%$/u, replacement: () => "★4 20% · ★3 77%" },
  { pattern: /^운명 가루 ([\d,]+)$/u, replacement: (_m, dust) => `Fate Dust ${dust}` },
  { pattern: /^운명 조각 \+(\d+) · 스토리 합류 대기$/u, replacement: (_m, shards) => `Fate Shards +${shards} · awaiting story recruitment` },
  { pattern: /^조각 \+(\d+) · 가루 \+(\d+)$/u, replacement: (_m, shards, dust) => `Shards +${shards} · Fate Dust +${dust}` },
  { pattern: /^소프트 천장 (\d+)회 · 확정 천장 (\d+)회 · ★5 픽업 (\d+)%$/u, replacement: (_m, soft, hard, featured) => `Soft pity ${soft} · hard pity ${hard} · ★5 featured rate ${featured}%` },
  { pattern: /^중복은 조각과 운명 가루로 변환 · 가루 (\d+)개로 다음 ★5 픽업 확정$/u, replacement: (_m, dust) => `Duplicates convert into shards and Fate Dust · spend ${dust} Dust to guarantee the next ★5 featured hero` },
  { pattern: /^(.+) \[합류 전: 조각\]$/u, replacement: (_m, hero) => `${translateKnownTerm(hero ?? "")} [Before Joining: Shards]` },
  { pattern: /^배너 (.+) · 약관 v(.+) · (종료일 없는 상시 배너|기간 배너)$/u, replacement: (_m, banner, version, kind) => `Banner ${banner} · Terms v${version} · ${translateKnownTerm(kind ?? "")}` },
  { pattern: /^운명 가루가 (\d+)개 부족합니다\.$/u, replacement: (_m, amount) => `You need ${amount} more Fate Dust.` },
  { pattern: /^(.+) 같은 소환을 다시 누르면 이어서 확인합니다\.$/u, replacement: (_m, message) => `${translateKnownTerm(message ?? "")} Select the same summon again to continue verification.` },

  // Endgame status, rewards, modifiers, and gates.
  { pattern: /^캠페인 별 (\d+) \/ 129\s+·\s+보유 영웅 (\d+)명$/u, replacement: (_m, stars, heroes) => `Campaign Stars ${stars} / 129 · Owned Heroes ${heroes}` },
  { pattern: /^(\d+) \/ 30층$/u, replacement: (_m, floor) => `Floor ${floor} / 30` },
  { pattern: /^노드 (\d+) \/ 12$/u, replacement: (_m, node) => `Node ${node} / 12` },
  { pattern: /^주간 완주 (\d+) \/ (\d+)$/u, replacement: (_m, runs, limit) => `Weekly Clears ${runs} / ${limit}` },
  { pattern: /^토벌 열쇠 ([\d,]+)$/u, replacement: (_m, keys) => `Raid Keys ${keys}` },
  { pattern: /^인연 (\d+) \/ 99 · 다음 (\d+): (.+)$/u, replacement: (_m, level, next, reward) => `Bond ${level} / 99 · Next ${next}: ${translateKnownTerm(reward ?? "")}` },
  { pattern: /^인연 (\d+) \/ 99 · 모든 마일스톤 달성$/u, replacement: (_m, level) => `Bond ${level} / 99 · All Milestones Reached` },
  { pattern: /^폭풍 점수 ([\d,]+) \/ ([\d,]+) · 다음 (.+)$/u, replacement: (_m, score, nextScore, reward) => `Storm Score ${score} / ${nextScore} · Next: ${translateKnownTerm(reward ?? "")}` },
  { pattern: /^폭풍 점수 ([\d,]+) · 전 티어 달성$/u, replacement: (_m, score) => `Storm Score ${score} · All Tiers Reached` },
  { pattern: /^(\d+) · 보유 (\d+)$/u, replacement: (_m, cost, owned) => `${cost} · Owned ${owned}` },
  { pattern: /^(\d+)\/(\d+)칸$/u, replacement: (_m, used, capacity) => `${used}/${capacity} slots` },
  { pattern: /^스킬라 비늘 (\d+)\/(\d+) · 골드 ([\d,]+)$/u, replacement: (_m, scales, required, gold) => `Scylla Scales ${scales}/${required} · Gold ${gold}` },
  { pattern: /^권장 전투력 ([\d,]+) · (.+)$/u, replacement: (_m, power, objective) => `Recommended Power ${power} · ${translateObjective(objective ?? "")}` },
  { pattern: /^골드 ×([\d.]+) · XP ×([\d.]+) · 재료 ×([\d.]+)$/u, replacement: (_m, gold, xp, materials) => `Gold ×${gold} · XP ×${xp} · Materials ×${materials}` },
  { pattern: /^폭풍 항로 (\d+) \/ 12 · 하나를 선택하면 되돌릴 수 없습니다$/u, replacement: (_m, node) => `Storm Route ${node} / 12 · this choice cannot be undone` },
  { pattern: /^폭풍 유리 \+(\d+)$/u, replacement: (_m, amount) => `Storm Glass +${amount}` },
  { pattern: /^신탁탑 (\d+)층 보상$/u, replacement: (_m, floor) => `Oracle Tower Floor ${floor} Reward` },
  { pattern: /^폭풍 항로 (\d+)\/12 · 보상 ×([\d.]+)$/u, replacement: (_m, node, scale) => `Storm Route ${node}/12 · Rewards ×${scale}` },
  { pattern: /^스킬라 토벌 순환 (\d+)\/3 · (.+)$/u, replacement: (_m, tier, reward) => `Scylla Raid Cycle ${tier}/3 · ${translateKnownTerm(reward ?? "")}` },
  { pattern: /^(\d+)층 · 사용 영웅 (\d+)층 잠금$/u, replacement: (_m, floor, lock) => `Floor ${floor} · used heroes locked for ${lock} floors` },
  { pattern: /^쓰러진 영웅 잠금 · 자유 교대 (\d+)회$/u, replacement: (_m, swaps) => `Fallen heroes locked · ${swaps} free swap${swaps === "1" ? "" : "s"}` },
  { pattern: /^신탁탑 (\d+)층 · (.+)$/u, replacement: (_m, floor, stage) => `Oracle Tower Floor ${floor} · ${translateKnownTerm(stage ?? "")}` },
  { pattern: /^폭풍 (\d+)\/12 · (.+)$/u, replacement: (_m, node, stage) => `Storm ${node}/12 · ${translateKnownTerm(stage ?? "")}` },
  { pattern: /^스킬라 (\d+)페이즈 · (.+)$/u, replacement: (_m, phase, name) => `Scylla Phase ${phase} · ${translateKnownTerm(name ?? "")}` },
  { pattern: /^(\d+)개 목표 · (\d+)턴$/u, replacement: (_m, objectives, turns) => `${objectives} Objectives · ${turns} Turns` },
  { pattern: /^이전 파괴 상태 (\d+)개 계승$/u, replacement: (_m, count) => `${count} destroyed-part states carried over` },
  { pattern: /^(\d+)페이즈 · (.+)$/u, replacement: (_m, phase, name) => `Phase ${phase} · ${translateKnownTerm(name ?? "")}` },
  { pattern: /^(보스|정예|적) HP ([+-]?\d+)%$/u, replacement: (_m, target, value) => `${target === "보스" ? "Boss" : target === "정예" ? "Elite" : "Enemy"} HP ${value}%` },
  { pattern: /^적 카운트 ([+-]?\d+)$/u, replacement: (_m, value) => `Enemy Countdown ${value}` },
  { pattern: /^예상 반사 (\d+)회$/u, replacement: (_m, count) => `Predicted Ricochets ${count}` },
  { pattern: /^(.+) 출전 금지$/u, replacement: (_m, heroClass) => `${translateKnownTerm(heroClass ?? "")} Forbidden` },
  { pattern: /^파티 ([A-Z]+) ([+-]?\d+)%$/u, replacement: (_m, stat, value) => `Party ${stat} ${value}%` },
  { pattern: /^최대 반사 (\d+)회$/u, replacement: (_m, count) => `Maximum Ricochets ${count}` },
  { pattern: /^거울벽 (\d+)개 생성$/u, replacement: (_m, count) => `Create ${count} Mirror Walls` },
  { pattern: /^가호 · (.+): (.+)$/u, replacement: (_m, blessing, effects) => `Blessing · ${translateKnownTerm(blessing ?? "")}: ${translateCompound(effects ?? "")}` },
  { pattern: /^예상 반사 \+(\d+)회 \(총 (\d+)회\)$/u, replacement: (_m, bonus, total) => `Predicted Ricochets +${bonus} (Total ${total})` },
  { pattern: /^(.+) · 주간 점수 ([\d,]+)(.*)$/u, replacement: (_m, mode, score, tiers) => `${translateKnownTerm(mode ?? "")} · Weekly Score ${score}${tiers ? translateCompound(tiers) : ""}` },
  { pattern: /^(.+) · 항해 인연 (\d+)\/99(.*)$/u, replacement: (_m, mode, bond, milestones) => `${translateKnownTerm(mode ?? "")} · Voyage Bond ${bond}/99${milestones ? translateCompound(milestones) : ""}` },
  { pattern: /^스킬라 (\d+)페이즈 돌파$/u, replacement: (_m, phase) => `Scylla Phase ${phase} Cleared` },
  { pattern: /^점수 보상 (.+)$/u, replacement: (_m, rewards) => `Score Rewards ${translateCompound(rewards ?? "")}` },
  { pattern: /^캠페인 별 (\d+)개가 필요합니다\.$/u, replacement: (_m, stars) => `${stars} campaign stars are required.` },
  { pattern: /^서로 겹치지 않는 3개 토벌대를 위해 영웅 (\d+)명이 필요합니다\.$/u, replacement: (_m, heroes) => `${heroes} unique heroes are required for three non-overlapping raid squads.` },

  // Party recommendation diagnostics.
  { pattern: /^권장 전투력 충족 · \+([\d,]+)$/u, replacement: (_m, surplus) => `Recommended Power Met · +${surplus}` },
  { pattern: /^(고위험|주의) · 권장보다 ([\d,]+) 부족$/u, replacement: (_m, level, deficit) => `${level === "고위험" ? "High Risk" : "Caution"} · ${deficit} below recommended` },
  { pattern: /^(\d+)개 지형 위험$/u, replacement: (_m, hazards) => `${hazards} Terrain Hazard${hazards === "1" ? "" : "s"}` },
  { pattern: /^(.+) 대응 점수가 높은 선원을 배치했습니다\.$/u, replacement: (_m, risks) => `Selected crew with strong counters to ${translateCompound((risks ?? "").replaceAll("·", " · "))}.` },
  { pattern: /^선택 인원보다 출전 가능한 영웅이 적어 (\d+)명만 추천했습니다\.$/u, replacement: (_m, count) => `Only ${count} available hero${count === "1" ? " was" : "es were"} recommended.` },
  { pattern: /^전투력 ([\d,]+)으로 권장을 충족합니다\.$/u, replacement: (_m, power) => `Power ${power} meets the recommendation.` },
  { pattern: /^전투력 ([\d,]+) · (.+)$/u, replacement: (_m, power, assessment) => `Power ${power} · ${translateKnownTerm(assessment ?? "")}` },

  // Relic effect formatting.
  { pattern: /^(.+) · 현재 미연결$/u, replacement: (_m, effect) => `${translateKnownTerm(effect ?? "")} · Currently Unsupported` },
  { pattern: /^(\d+)턴 감소$/u, replacement: (_m, turns) => `${turns} turn${turns === "1" ? "" : "s"} reduction` },
  { pattern: /^(\d+)턴$/u, replacement: (_m, turns) => `${turns} turn${turns === "1" ? "" : "s"}` },
  { pattern: /^첫 돌파 · (.+?)(?: ×(\d+))?$/u, replacement: (_m, reward, amount) => `First Clear · ${translateKnownTerm(reward ?? "")}${amount ? ` ×${amount}` : ""}` },
  { pattern: /^스토리 승선 · (.+)$/u, replacement: (_m, heroes) => `Story Recruitment · ${translateCharacterList(heroes ?? "")}` },
  { pattern: /^무료 토벌 열쇠 ×(\d+)$/u, replacement: (_m, amount) => `Free Raid Keys ×${amount}` },

  // Developer cabin live status.
  { pattern: /^스토리 (\d+)\/(\d+)\s+·\s+선원 (\d+)\/(\d+)$/u, replacement: (_m, story, totalStory, crew, totalCrew) => `Story ${story}/${totalStory} · Crew ${crew}/${totalCrew}` },
  { pattern: /^토벌 열쇠 (\d+)\s+·\s+골드 ([\d,]+)\s+·\s+실제 다이아 사용 차단$/u, replacement: (_m, keys, gold) => `Raid Keys ${keys} · Gold ${gold} · Real Diamond spending blocked` },
  { pattern: /^(.+) 완료 · 이 탭의 휘발성 시험 저장에만 적용되었습니다\.$/u, replacement: (_m, action) => `${translateKnownTerm(action ?? "")} complete · applied only to this tab's volatile test save.` },
  { pattern: /^(.+) 실패 · (.+)$/u, replacement: (_m, action, error) => `${translateKnownTerm(action ?? "")} failed · ${error}` },
]);
